const library = [{
    url: 'https://www.baidu.com/',
    imgSrc: './logos/baidu.png',
    title: '百度'
}, {
    url: 'https://cn.vuejs.org/',
    imgSrc: './logos/vue.png',
    title: 'Vue.js'
}, {
    url: 'https://doc.react-china.org/',
    imgSrc: './logos/react.png',
    title: 'React.js'
}, {
    url: 'https://angular.cn/',
    imgSrc: './logos/angular.png',
    title: 'Angular.js'
}, {
    url: 'https://webpack.js.org/',
    imgSrc: './logos/webpack.png',
    title: 'webpack'
}, {
    url: 'https://www.gulpjs.com.cn/',
    imgSrc: './logos/gulp.png',
    title: 'gulp'
}, {
    url: 'http://eslint.cn/',
    imgSrc: './logos/eslint.png',
    title: 'eslint'
}, {
    url: 'http://babeljs.io/',
    imgSrc: './logos/babel.png',
    title: 'babel'
}, {
    url: 'https://www.tslang.cn/',
    imgSrc: './logos/typescript.png',
    title: 'TypeScript'
}, {
    url: 'http://jquery.cuishifeng.cn/',
    imgSrc: './logos/jquery.png',
    title: 'jQuery'
}, {
    url: 'https://github.com/',
    imgSrc: './logos/github.png',
    title: 'github'
}, {
    url: 'https://segmentfault.com/',
    imgSrc: './logos/sf.png',
    title: 'segmentfault'
}, {
    url: 'https://developer.mozilla.org/zh-CN/',
    imgSrc: './logos/MDN.png',
    title: 'MDN'
}, {
    url: 'https://www.zhihu.com/',
    imgSrc: './logos/zhihu.png',
    title: '知乎'
}, {
    url: 'https://juejin.im/timeline',
    imgSrc: './logos/juejin.png',
    title: '掘金'
}, {
    url: 'https://mp.weixin.qq.com/debug/wxadoc/dev/framework/MINA.html',
    imgSrc: './logos/xcx.png',
    title: '微信小程序'
}, {
    url: 'http://nodejs.cn/api/',
    imgSrc: './logos/nodejs.png',
    title: 'nodeJS'
}, {
    url: 'http://expressjs.com/',
    imgSrc: './logos/express.png',
    title: 'expressjs'
}, {
    url: 'https://electronjs.org/',
    imgSrc: './logos/electron.png',
    title: 'electron'
}, {
    url: 'https://www.sass.hk/',
    imgSrc: './logos/sass.png',
    title: 'sass'
}, {
    url: 'http://lesscss.cn/',
    imgSrc: './logos/less.png',
    title: 'less'
}, {
    url: 'https://studygolang.com/',
    imgSrc: './logos/golang.png',
    title: 'go'
}, {
    url: 'https://ruby-china.org/',
    imgSrc: './logos/ruby.png',
    title: 'ruby'
}, {
    url: 'hhttp://www.iconfont.cn/',
    imgSrc: './logos/iconfont.png',
    title: 'iconfont'
}, {
    url: 'https://kb.cnblogs.com/',
    imgSrc: './logos/bokeyuan.png',
    title: '博客园'
}, {
    url: 'https://www.jianshu.com/',
    imgSrc: './logos/jianshu.png',
    title: '简书'
}, {
    url: 'http://web.jobbole.com/',
    imgSrc: './logos/jobbole.png',
    title: '伯乐在线'
}];