export default <AppItem[]>[
  {
    homepage: 'https://openai.com/',
    repository: 'https://github.com/openai',
    icon: 'openai.png',
    keywords: ['openai', 'gpt', 'chatgpt', 'ai'],
    name: 'OpenAI',
    darkInvert: true,
  },
  {
    homepage: 'https://claude.ai/',
    icon: 'claude.png',
    keywords: ['claude', 'ai', 'anthropic'],
    name: 'Claude',
    lessRadius: true,
  },
  {
    homepage: 'https://gemini.google.com/',
    icon: 'gemini.png',
    keywords: ['gemini', 'ai'],
    name: 'Gemini',
  },
  {
    homepage: 'https://grok.com/',
    repository: 'https://github.com/xai-org',
    icon: 'grok.png',
    keywords: ['grok', 'ai'],
    name: 'Grok',
    darkInvert: true,
  },
  {
    homepage: 'https://www.deepseek.com',
    repository: 'https://github.com/deepseek-ai',
    icon: 'deepseek.png',
    keywords: ['deepseek', 'ai'],
    name: 'DeepSeek',
  },
  {
    homepage: 'https://kimi.moonshot.cn/',
    icon: 'kimi.png',
    keywords: ['kimi', 'ai'],
    name: 'Kimi',
  },
  {
    homepage: 'https://tongyi.aliyun.com/',
    icon: 'tongyi.png',
    keywords: ['tongyi', '通义', 'ai'],
    name: '通义',
  },
  {
    homepage: 'https://bigmodel.cn/',
    repository: 'https://github.com/zai-org',
    icon: 'zhipu.png',
    keywords: ['bigmodel', 'zhipu', '智谱', 'glm', 'ai'],
    name: '智谱',
  },
  {
    homepage: 'https://www.minimaxi.com/',
    repository: 'https://github.com/MiniMax-AI',
    icon: 'minimax.png',
    keywords: ['minimax', 'ai'],
    name: 'MiniMax',
  },
  {
    homepage: 'https://yiyan.baidu.com/',
    icon: 'wenxinyiyan.png',
    keywords: ['wenxinyiyan', '文心一言', 'ai'],
    name: '文心一言',
  },
  {
    homepage: 'https://ollama.com/',
    repository: 'https://github.com/ollama/ollama',
    icon: 'ollama.png',
    keywords: ['ollama', 'ai'],
    name: 'Ollama',
    darkInvert: true,
  },
  {
    homepage: 'https://opencode.ai/',
    repository: 'https://github.com/anomalyco/opencode',
    icon: 'opencode.png',
    keywords: ['opencode', 'ai'],
    name: 'OpenCode',
    lessRadius: true,
  },
  {
    homepage: 'https://huggingface.co/',
    repository: 'https://github.com/huggingface',
    icon: 'huggingface.png',
    keywords: ['huggingface', 'ai'],
    name: 'Hugging Face',
  },
  {
    homepage: 'https://www.perplexity.ai/',
    icon: 'perplexity.png',
    keywords: ['perplexity', 'ai'],
    name: 'Perplexity',
  },
  {
    homepage: 'https://v0.dev/',
    icon: 'v0.png',
    keywords: ['v0', 'ai'],
    name: 'v0',
    darkInvert: true,
  },
  {
    homepage: 'https://bolt.new/',
    icon: 'bolt.png',
    keywords: ['bolt', 'ai'],
    name: 'Bolt',
    darkInvert: true,
  },
  {
    homepage: 'https://runwayml.com/',
    icon: 'runway.png',
    keywords: ['runway', 'ai'],
    name: 'Runway',
    darkInvert: true,
  },
  {
    homepage: 'https://manus.im/',
    icon: 'manus.png',
    keywords: ['manus', 'ai'],
    name: 'Manus',
    darkInvert: true,
  },
  {
    homepage: 'https://www.coze.com/',
    icon: 'coze.png',
    keywords: ['coze', 'ai'],
    name: 'Coze',
  },
]
