export default <AppItem[]>[
  {
    homepage: 'https://react.dev/',
    repository: 'https://github.com/facebook/react/',
    icon: 'react.png',
    keywords: ['react'],
    name: 'React',
  },
  {
    homepage: 'https://vuejs.org/',
    repository: 'https://github.com/vuejs/core',
    icon: 'vue.png',
    keywords: ['vue'],
    name: 'Vue',
    lessRadius: true,
  },
  {
    homepage: 'https://angular.dev/',
    repository: 'https://github.com/angular/angular',
    icon: 'angular.png',
    keywords: ['angular'],
    name: 'Angular',
  },
  {
    homepage: 'https://svelte.dev/',
    repository: 'https://github.com/sveltejs/svelte',
    icon: 'svelte.png',
    keywords: ['svelte'],
    name: 'Svelte',
  },
  {
    homepage: 'https://www.solidjs.com/',
    repository: 'https://github.com/solidjs/solid',
    icon: 'solidjs.png',
    keywords: ['solidjs'],
    name: 'Solid',
  },
  {
    homepage: 'https://preactjs.com/',
    repository: 'https://github.com/preactjs/preact',
    icon: 'preactjs.png',
    keywords: ['preactjs', 'react'],
    name: 'Preactjs',
  },
  {
    homepage: 'https://yew.rs',
    repository: 'https://github.com/yewstack/yew',
    icon: 'yew.png',
    keywords: ['yew', 'rust', 'wasm'],
    name: 'Yew',
  },
  {
    homepage: 'https://emberjs.com/',
    repository: 'https://github.com/emberjs/ember.js/',
    icon: 'ember.png',
    keywords: ['ember'],
    name: 'Ember',
  },
  {
    homepage: 'https://lit.dev/',
    repository: 'https://github.com/lit/lit',
    icon: 'lit.png',
    keywords: ['lit'],
    name: 'Lit',
  },
  {
    homepage: 'https://ice.work/',
    repository: 'https://github.com/alibaba/ice',
    icon: 'ice.png',
    keywords: ['icejs', 'react'],
    name: 'Ice',
  },
  {
    homepage: 'https://dvajs.com/',
    repository: 'https://github.com/dvajs/dva',
    icon: 'dvajs.png',
    keywords: ['dvajs', 'react'],
    name: 'DvaJS',
  },
  {
    homepage: 'https://infernojs.org/',
    repository: 'https://github.com/infernojs/inferno',
    icon: 'infernojs.png',
    keywords: ['infernojs', 'react'],
    name: 'Inferno',
  },
  {
    homepage: 'https://umijs.org/',
    repository: 'https://github.com/umijs/umi',
    icon: 'umi.png',
    keywords: ['umi', 'react'],
    name: 'Umi',
  },
  {
    homepage: 'https://markojs.com/',
    repository: 'https://github.com/marko-js/marko/',
    icon: 'marko.png',
    keywords: ['marko'],
    name: 'Marko',
  },
  {
    homepage: 'https://stimulus.hotwired.dev/',
    repository: 'https://github.com/hotwired/stimulus',
    icon: 'stimulus.png',
    keywords: ['stimulus'],
    name: 'Stimulus',
  },
  {
    homepage: 'https://reasonml.github.io/',
    repository: 'https://github.com/reasonml/reason',
    icon: 'reason.png',
    keywords: ['reason'],
    name: 'Reason',
    lessRadius: true,
  },
  {
    homepage: 'https://nerv.aotu.io/',
    repository: 'https://github.com/NervJS/nerv',
    icon: 'nervjs.png',
    keywords: ['nervjs', 'react'],
    name: 'NervJS',
  },
  {
    homepage: 'http://aurelia.io/',
    repository: 'https://github.com/aurelia/aurelia',
    icon: 'aurelia.png',
    keywords: ['aurelia'],
    name: 'Aurelia',
  },

  {
    homepage: 'https://nextjs.org/',
    repository: 'https://github.com/vercel/next.js',
    icon: 'next.png',
    keywords: ['next.js', 'react'],
    name: 'Next.js',
  },
  {
    homepage: 'https://nuxt.com/',
    repository: 'https://github.com/nuxt/nuxt.js',
    icon: 'nuxt.png',
    keywords: ['nuxt', 'vue'],
    name: 'Nuxt',
  },
  {
    homepage: 'https://remix.run/',
    repository: 'https://github.com/remix-run/remix',
    icon: 'remix.png',
    keywords: ['remix'],
    name: 'Remix',
    darkInvert: true,
  },
  {
    homepage: 'https://qwik.dev/',
    repository: 'https://github.com/BuilderIO/qwik',
    icon: 'qwik.png',
    keywords: ['qwik'],
    name: 'Qwik',
  },
  {
    homepage: 'https://fresh.deno.dev/',
    repository: 'https://github.com/denoland/fresh',
    icon: 'fresh.png',
    keywords: ['fresh'],
    name: 'Fresh',
  },
  {
    homepage: 'https://analogjs.org/',
    repository: 'https://github.com/analogjs/analog',
    icon: 'analog.png',
    keywords: ['analog', 'angular'],
    name: 'Analog',
  },
  {
    homepage: 'https://sst.dev/',
    repository: 'https://github.com/sst/sst',
    icon: 'sst.png',
    keywords: ['sst'],
    name: 'SST',
  },
  {
    homepage: 'https://redwoodjs.com/',
    repository: 'https://github.com/redwoodjs/redwood',
    icon: 'redwoodjs.png',
    keywords: ['redwoodjs'],
    name: 'Redwood',
  },
  {
    homepage: 'https://imba.io/',
    repository: 'https://github.com/imba/imba',
    icon: 'imba.png',
    keywords: ['imba'],
    name: 'Imba',
  },

  {
    homepage: 'https://gohugo.io/',
    repository: 'https://github.com/gohugoio/hugo',
    icon: 'hugo.png',
    keywords: ['hugo'],
    name: 'Hugo',
  },
  {
    homepage: 'https://www.gatsbyjs.com/',
    repository: 'https://github.com/gatsbyjs/gatsby',
    icon: 'gatsby.png',
    keywords: ['gatsby'],
    name: 'Gatsby',
  },
  {
    homepage: 'https://astro.build/',
    repository: 'https://github.com/withastro/astro',
    icon: 'astro.png',
    keywords: ['astro'],
    name: 'Astro',
  },
  {
    homepage: 'https://jekyllrb.com/',
    repository: 'https://github.com/jekyll/jekyll',
    icon: 'jekyll.png',
    keywords: ['jekyll'],
    name: 'Jekyll',
  },
  {
    homepage: 'https://gridsome.org/',
    repository: 'https://github.com/gridsome/gridsome',
    icon: 'gridsome.png',
    keywords: ['gridsome', 'vue'],
    name: 'Gridsome',
  },
  {
    homepage: 'https://docusaurus.io/',
    repository: 'https://github.com/facebook/docusaurus',
    icon: 'docusaurus.png',
    keywords: ['docusaurus'],
    name: 'Docusaurus',
  },
  {
    homepage: 'https://vitepress.dev/',
    repository: 'https://github.com/vuejs/vitepress',
    icon: 'vitepress.png',
    keywords: ['vitepress'],
    name: 'VitePress',
  },
  {
    homepage: 'https://vuepress.vuejs.org/',
    repository: 'https://github.com/vuejs/vuepress',
    icon: 'vuepress.png',
    keywords: ['vuepress'],
    name: 'VuePress',
  },
  {
    homepage: 'https://github.com/react-static/react-static',
    repository: 'https://github.com/react-static/react-static',
    icon: 'react-static.png',
    keywords: ['react-static', 'react'],
    name: 'ReactStatic',
  },
  {
    homepage: 'https://starlight.astro.build/',
    repository: 'https://github.com/withastro/starlight',
    icon: 'starlight.png',
    keywords: ['starlight'],
    name: 'Starlight',
  },
  {
    homepage: 'https://d.umijs.org/',
    repository: 'https://github.com/umijs/dumi',
    icon: 'dumi.png',
    keywords: ['dumi'],
    name: 'Dumi',
  },
  {
    homepage: 'https://flutter.dev/',
    repository: 'https://github.com/flutter/flutter',
    icon: 'flutter.png',
    keywords: ['flutter'],
    name: 'Flutter',
  },
  {
    homepage: 'https://reactnative.dev/',
    repository: 'https://github.com/facebook/react-native',
    icon: 'react-native.png',
    keywords: ['reactnative', 'react', 'rn'],
    name: 'ReactNative',
  },
  {
    homepage: 'https://www.electronjs.org/',
    repository: 'https://github.com/electron/electron',
    icon: 'electron.png',
    keywords: ['electron'],
    name: 'Electron',
  },
  {
    homepage: 'https://tauri.app/',
    repository: 'https://github.com/tauri-apps/tauri',
    icon: 'tauri.png',
    keywords: ['tauri'],
    name: 'Tauri',
  },
  {
    homepage: 'https://ionic.io/',
    repository: 'https://github.com/ionic-team',
    icon: 'ionic.png',
    keywords: ['ionic'],
    name: 'Ionic',
  },
  {
    homepage: 'https://docs.taro.zone/',
    repository: 'https://github.com/NervJS/taro',
    icon: 'taro.png',
    keywords: ['taro', 'nerv', 'react'],
    name: 'Taro',
  },
  {
    homepage: 'https://nativescript.org/',
    repository: 'https://github.com/NativeScript/NativeScript',
    icon: 'nativescript.png',
    keywords: ['nativescript'],
    name: 'NativeScript',
  },
  {
    homepage: 'https://weexapp.com/',
    repository: 'https://github.com/alibaba/weex',
    icon: 'weex.png',
    keywords: ['weex', 'vue'],
    name: 'Weex',
  },
  {
    homepage: 'https://hippyjs.org/#/',
    repository: 'https://github.com/Tencent/Hippy',
    icon: 'hippy.png',
    keywords: ['hippyjs', 'vue', 'react'],
    name: 'Hippy',
  },
  {
    homepage: 'https://openkraken.com/',
    repository: 'https://github.com/openkraken/kraken',
    icon: 'kraken.png',
    keywords: ['kraken', 'flutter'],
    name: 'Kraken',
  },
  {
    homepage: 'https://openwebf.com/',
    repository: 'https://github.com/openwebf/webf',
    icon: 'webf.png',
    keywords: ['webf'],
    name: 'WebF',
    lessRadius: true,
  },
  {
    homepage: 'https://rax.js.org/',
    repository: 'https://github.com/alibaba/rax',
    icon: 'rax.png',
    keywords: ['rax'],
    name: 'Rax',
  },
  {
    homepage: 'https://mpxjs.cn/',
    repository: 'https://github.com/didi/mpx',
    icon: 'mpx.png',
    keywords: ['mpx'],
    name: 'Mpx',
  },
  {
    homepage: 'https://cml.js.org/',
    repository: 'https://github.com/didi/chameleon',
    icon: 'chameleon.png',
    keywords: ['chameleon'],
    name: 'Chameleon',
  },
  {
    homepage: 'https://developers.weixin.qq.com/miniprogram/dev/framework/',
    icon: 'wechatmp.png',
    keywords: ['微信小程序', 'weixin', 'wechat', 'xiaochengxu', 'miniapp', 'miniprogram', 'microapp', 'mp'],
    name: '微信小程序',
  },
  {
    homepage: 'https://mp.jd.com/',
    icon: 'jdmp.png',
    keywords: ['京东小程序', 'jingdong', 'jdmp', 'xiaochengxu', 'miniapp', 'miniprogram', 'microapp', 'mp'],
    name: '京东小程序',
  },
  {
    homepage: 'https://smartprogram.baidu.com/',
    icon: 'bdmp.png',
    keywords: ['百度智能小程序', 'baiduzhineng', 'xiaochengxu', 'miniapp', 'miniprogram', 'microapp', 'mp'],
    name: '智能小程序',
  },
  {
    homepage: 'https://open.alipay.com/',
    icon: 'alipaymp.png',
    keywords: [
      '支付宝开放平台',
      '支付宝小程序',
      'zhifubao',
      'alipay',
      'xiaochengxu',
      'miniapp',
      'miniprogram',
      'microapp',
      'mp',
    ],
    name: '支付宝开放平台',
  },
  {
    homepage: 'https://developer.open-douyin.com/',
    icon: 'douyin.png',
    keywords: ['抖音开放平台', 'douyin', 'xiaochengxu', 'miniapp', 'miniprogram', 'microapp', 'mp'],
    name: '抖音开放平台',
    darkInvert: true,
  },
  {
    homepage: 'https://q.qq.com/',
    icon: 'qqmp.png',
    keywords: ['qq开放平台', 'qq', 'xiaochengxu', 'miniapp', 'miniprogram', 'microapp', 'mp'],
    name: 'QQ开放平台',
  },
  {
    homepage: 'https://open.dingtalk.com/',
    icon: 'dingtalk.png',
    keywords: ['dingding', 'dingtalk', 'xiaochengxu', 'miniapp', 'miniprogram', 'microapp', 'mp'],
    name: '钉钉开放平台',
  },
  {
    homepage: 'https://open.feishu.cn/',
    icon: 'feishu.png',
    keywords: ['feishu', 'xiaochengxu', 'miniapp', 'miniprogram', 'microapp', 'mp'],
    name: '飞书开放平台',
  },
  {
    homepage: 'https://open.kuaishou.com/',
    icon: 'kuaishou.png',
    keywords: ['kuaishou', 'xiaochengxu', 'miniapp', 'miniprogram', 'microapp', 'mp'],
    name: '快手开放平台',
  },
  {
    homepage: 'https://www.quickapp.cn/',
    icon: 'kyy.png',
    keywords: ['快应用', 'kuaiyingyong'],
    name: '快应用',
  },
]
