export default <AppItem[]>[
  {
    homepage: 'https://webpack.js.org/',
    repository: 'https://github.com/webpack/webpack',
    icon: 'webpack.png',
    keywords: ['webpack'],
    name: 'Webpack',
  },
  {
    homepage: 'https://turbo.build/pack/',
    repository: 'https://github.com/vercel/turbo',
    icon: 'turbopack.png',
    keywords: ['turbopack'],
    name: 'Turbopack',
  },
  {
    homepage: 'https://www.rspack.dev/',
    repository: 'https://github.com/web-infra-dev/rspack',
    icon: 'rspack.png',
    keywords: ['rspack'],
    name: 'Rspack',
  },
  {
    homepage: 'https://esbuild.github.io/',
    repository: 'https://github.com/evanw/esbuild',
    icon: 'esbuild.png',
    keywords: ['esbuild'],
    name: 'Esbuild',
  },
  {
    homepage: 'https://swc.rs/',
    repository: 'https://github.com/swc-project/swc',
    icon: 'swc.png',
    keywords: ['swc'],
    name: 'SWC',
  },
  {
    homepage: 'https://rollupjs.org/',
    repository: 'https://github.com/rollup/rollup',
    icon: 'rollup.png',
    keywords: ['rollup'],
    name: 'Rollup',
  },
  {
    homepage: 'https://rolldown.rs/',
    repository: 'https://github.com/rolldown/rolldown',
    icon: 'rolldown.png',
    keywords: ['rolldown'],
    name: 'Rolldown',
  },
  {
    homepage: 'https://parceljs.org/',
    repository: 'https://github.com/parcel-bundler/parcel',
    icon: 'parcel.png',
    keywords: ['parcel'],
    name: 'Parcel',
  },
  {
    homepage: 'https://www.farmfe.org/',
    repository: 'https://github.com/farm-fe/farm',
    icon: 'farm.png',
    keywords: ['farm'],
    name: 'Farm',
  },
  {
    homepage: 'https://www.snowpack.dev/',
    repository: 'https://github.com/FredKSchott/snowpack',
    icon: 'snowpack.png',
    keywords: ['snowpack'],
    name: 'Snowpack',
  },
  {
    homepage: 'https://wmr.dev/',
    repository: 'https://github.com/preactjs/wmr',
    icon: 'wmr.png',
    keywords: ['wmr'],
    name: 'WMR',
  },
  {
    homepage: 'https://prepack.io/',
    repository: 'https://github.com/facebookarchive/prepack',
    icon: 'prepack.png',
    keywords: ['prepack'],
    name: 'Prepack',
  },
  {
    homepage: 'https://gulpjs.com/',
    repository: 'https://github.com/gulpjs/gulp',
    icon: 'gulp.png',
    keywords: ['gulp'],
    name: 'Gulp',
  },
  {
    homepage: 'https://gruntjs.com/',
    repository: 'https://github.com/gruntjs/grunt',
    icon: 'grunt.png',
    keywords: ['grunt'],
    name: 'Grunt',
  },
  {
    homepage: 'http://browserify.org/',
    repository: 'https://github.com/browserify/browserify',
    icon: 'browserify.png',
    keywords: ['browserify'],
    name: 'Browserify',
  },
  {
    homepage: 'https://vitejs.dev/',
    repository: 'https://github.com/vitejs/vite',
    icon: 'vite.png',
    keywords: ['vite'],
    name: 'Vite',
  },
  {
    homepage: 'https://create-react-app.dev/',
    repository: 'https://github.com/facebook/create-react-app',
    icon: 'cra.png',
    keywords: ['cra', 'create-react-app'],
    name: 'CreateReactApp',
  },
  {
    homepage: 'https://github.com/google/zx',
    repository: 'https://github.com/google/zx',
    icon: 'zx.png',
    keywords: ['zx'],
    name: 'ZX',
  },
  {
    homepage: 'http://babeljs.io/',
    repository: 'https://github.com/babel/babel',
    icon: 'babel.png',
    keywords: ['babel'],
    name: 'Babel',
  },
  {
    homepage: 'https://eslint.org/',
    repository: 'https://github.com/eslint/eslint',
    icon: 'eslint.png',
    keywords: ['eslint'],
    name: 'ESlint',
  },
  {
    homepage: 'https://oxc.rs/',
    repository: 'https://github.com/oxc-project/oxc',
    icon: 'oxc.png',
    keywords: ['oxc'],
    name: 'Oxc',
  },
  {
    homepage: 'https://jshint.com/',
    repository: 'https://github.com/jshint/jshint',
    icon: 'jshint.png',
    keywords: ['jshint'],
    name: 'JSHint',
    lessRadius: true,
  },
  {
    homepage: 'https://flow.org/',
    repository: 'https://github.com/facebook/flow',
    icon: 'flow.png',
    keywords: ['flow'],
    name: 'Flow',
  },
  {
    homepage: 'https://prettier.io/',
    repository: 'https://github.com/prettier/prettier',
    icon: 'prettier.png',
    keywords: ['prettier'],
    name: 'Prettier',
    lessRadius: true,
  },
  {
    homepage: 'https://www.typescriptlang.org/',
    repository: 'https://github.com/Microsoft/TypeScript',
    icon: 'typescript.png',
    keywords: ['typescript', 'ts'],
    name: 'TypeScript',
  },
  {
    homepage: 'https://www.assemblyscript.org/',
    repository: 'https://github.com/AssemblyScript/assemblyscript',
    icon: 'assemblyscript.png',
    keywords: ['assemblyscript', 'as'],
    name: 'AssemblyScript',
  },
  {
    homepage: 'https://coffeescript.org/',
    repository: 'https://github.com/jashkenas/coffeescript',
    icon: 'coffeescript.png',
    keywords: ['coffeescript'],
    name: 'CoffeeScript',
    darkInvert: true,
  },
  {
    homepage: 'https://nodemon.io/',
    repository: 'https://github.com/remy/nodemon/',
    icon: 'nodemon.png',
    keywords: ['nodemon'],
    name: 'Nodemon',
  },
  {
    homepage: 'https://typestrong.org/ts-node/',
    repository: 'https://github.com/TypeStrong/ts-node',
    icon: 'ts-node.png',
    keywords: ['ts-node'],
    name: 'TSNode',
  },
  {
    homepage: 'https://terser.org/',
    repository: 'https://github.com/terser/terser',
    icon: 'terser.png',
    keywords: ['terser'],
    name: 'Terser',
  },
  {
    homepage: 'https://gogocode.io/zh',
    repository: 'https://github.com/thx/gogocode',
    icon: 'gogocode.png',
    keywords: ['gogocode'],
    name: 'GoGoCode',
  },
  {
    homepage: 'https://rxjs.dev/',
    repository: 'https://github.com/ReactiveX/rxjs',
    icon: 'rxjs.png',
    keywords: ['rxjs'],
    name: 'RxJS',
  },
  {
    homepage: 'https://pinia.vuejs.org/',
    repository: 'https://github.com/vuejs/pinia',
    icon: 'pinia.png',
    keywords: ['pinia'],
    name: 'Pinia',
  },
  {
    homepage: 'https://redux.js.org/',
    repository: 'https://github.com/reduxjs/redux',
    icon: 'redux.png',
    keywords: ['redux'],
    name: 'Redux',
  },
  {
    homepage: 'https://reactrouter.com/',
    repository: 'https://github.com/remix-run/react-router',
    icon: 'react-router.png',
    keywords: ['reactrouter'],
    name: 'ReactRouter',
  },
  {
    homepage: 'https://graphql.org/',
    repository: 'https://github.com/graphql/graphiql',
    icon: 'graphql.png',
    keywords: ['graphql'],
    name: 'GraphQL',
  },
  {
    homepage: 'https://www.apollographql.com/',
    repository: 'https://github.com/apollographql',
    icon: 'apollographql.png',
    keywords: ['apollographql'],
    name: 'Apollo',
  },
  {
    homepage: 'https://nx.dev/',
    repository: 'https://github.com/nrwl/nx',
    icon: 'nx.png',
    keywords: ['nx'],
    name: 'Nx',
    darkInvert: true,
  },
  {
    homepage: 'https://lerna.js.org/',
    repository: 'https://github.com/lerna/lerna',
    icon: 'lerna.png',
    keywords: ['lerna'],
    name: 'Lerna',
    darkInvert: true,
  },
  {
    homepage: 'https://turbo.build/repo/',
    repository: 'https://github.com/vercel/turbo',
    icon: 'turborepo.png',
    keywords: ['turborepo'],
    name: 'Turborepo',
  },
  {
    homepage: 'https://pre-commit.com/',
    repository: 'https://github.com/pre-commit/pre-commit',
    icon: 'pre-commit.png',
    keywords: ['pre-commit'],
    name: 'PreCommit',
  },
  {
    homepage: 'https://lodash.com/',
    repository: 'https://github.com/lodash/lodash/',
    icon: 'lodash.png',
    keywords: ['lodash'],
    name: 'Lodash',
  },
  {
    homepage: 'https://vueuse.org/',
    repository: 'https://github.com/vueuse/vueuse',
    icon: 'vueuse.png',
    keywords: ['vueuse'],
    name: 'VueUse',
  },
  {
    homepage: 'https://inhiblabcore.github.io/docs/hooks/',
    repository: 'https://github.com//InhiblabCore/vue-hooks-plus',
    icon: 'vue-hooks-plus.png',
    keywords: ['vuehooksplus'],
    name: 'VueHooks Plus',
    lessRadius: true,
  },
  {
    homepage: 'https://ahooks.js.org/',
    repository: 'https://github.com/alibaba/hooks',
    icon: 'ahooks.png',
    keywords: ['ahooks', 'react'],
    name: 'Ahooks',
  },
  {
    homepage: 'https://vue-vine.dev/',
    repository: 'https://github.com/vue-vine/vue-vine',
    icon: 'vue-vine.png',
    keywords: ['vue-vine'],
    name: 'Vue Vine',
  },
  {
    homepage: 'https://dojotoolkit.org/',
    repository: 'https://github.com/dojo/dojo',
    icon: 'dojo.png',
    keywords: ['dojo'],
    name: 'Dojo',
  },
  {
    homepage: 'https://immutable-js.github.io/immutable-js/',
    repository: 'https://github.com/immutable-js/immutable-js',
    icon: 'immutable.png',
    keywords: ['immutable'],
    name: 'Immutable',
  },
  {
    homepage: 'https://jquery.com/',
    repository: 'https://github.com/jquery/jquery',
    icon: 'jquery.png',
    keywords: ['jquery'],
    name: 'jQuery',
  },
  {
    homepage: 'https://zeptojs.com/',
    repository: 'https://github.com/madrobby/zepto/',
    icon: 'zepto.png',
    keywords: ['zepto'],
    name: 'Zepto',
  },
  {
    homepage: 'https://floating-ui.com/',
    repository: 'https://github.com/floating-ui/floating-ui',
    icon: 'floating-ui.png',
    keywords: ['floating-ui'],
    name: 'Floating UI',
  },
  {
    homepage: 'https://svelte-sonner.vercel.app/',
    repository: 'https://github.com/wobsoriano/svelte-sonner',
    icon: 'svelte-sonner.png',
    keywords: ['svelte-sonner'],
    name: 'Svelte Sonner',
  },
  {
    homepage: 'https://sli.dev/',
    repository: 'https://github.com/slidevjs/slidev',
    icon: 'slidev.png',
    keywords: ['slidev'],
    name: 'Slidev',
  },
  {
    homepage: 'https://axios-http.com/',
    repository: 'https://github.com/axios/axios',
    icon: 'axios.png',
    keywords: ['axios'],
    name: 'Axios',
    darkInvert: true,
  },
  {
    homepage: 'https://swr.vercel.app/',
    repository: 'https://github.com/vercel/swr',
    icon: 'swr.png',
    keywords: ['swr'],
    name: 'SWR',
  },
  {
    homepage: 'http://mockjs.com/',
    repository: 'https://github.com/nuysoft/Mock',
    icon: 'mockjs.png',
    keywords: ['mockjs'],
    name: 'MockJS',
  },
  {
    homepage: 'https://fakerjs.dev/',
    repository: 'https://github.com/faker-js/faker',
    icon: 'faker.png',
    keywords: ['faker'],
    name: 'faker',
  },
  {
    homepage: 'https://react-hook-form.com/',
    repository: 'https://github.com/react-hook-form/react-hook-form',
    icon: 'react-hook-form.png',
    keywords: ['react-hook-form'],
    name: 'ReactHookForm',
  },
  {
    homepage: 'https://www.embla-carousel.com/',
    repository: 'https://github.com/davidjerleke/embla-carousel',
    icon: 'embla-carousel.png',
    keywords: ['embla-carousel'],
    name: 'EmblaCarousel',
  },
  {
    homepage: 'https://zod.dev/',
    repository: 'https://github.com/colinhacks/zod',
    icon: 'zod.png',
    keywords: ['zod'],
    name: 'Zod',
  },
  {
    homepage: 'https://momentjs.com/',
    repository: 'https://github.com/moment/moment',
    icon: 'moment.png',
    keywords: ['moment'],
    name: 'Moment',
  },
  {
    homepage: 'https://day.js.org/',
    repository: 'https://github.com/iamkun/dayjs',
    icon: 'dayjs.png',
    keywords: ['dayjs'],
    name: 'DayJS',
  },
  {
    homepage: 'https://date-fns.org/',
    repository: 'https://github.com/date-fns/date-fns',
    icon: 'date-fns.png',
    keywords: ['date-fns'],
    name: 'DateFNS',
  },
  {
    homepage: 'https://playwright.dev/',
    repository: 'https://github.com/microsoft/playwright',
    icon: 'playwright.png',
    keywords: ['playwright'],
    name: 'playwright',
  },
  {
    homepage: 'https://jestjs.io/',
    repository: 'https://github.com/facebook/jest',
    icon: 'jest.png',
    keywords: ['jest'],
    name: 'Jest',
  },
  {
    homepage: 'https://mochajs.org/',
    repository: 'https://github.com/mochajs/mocha',
    icon: 'mocha.png',
    keywords: ['mocha'],
    name: 'Mocha',
  },
  {
    homepage: 'https://vitest.dev/',
    repository: 'https://github.com/vitest-dev/vitest',
    icon: 'vitest.png',
    keywords: ['vitest'],
    name: 'Vitest',
  },
  {
    homepage: 'https://testing-library.com/',
    repository: 'https://github.com/testing-library',
    icon: 'testing-library.png',
    keywords: ['testing-library'],
    name: 'TestingLibrary',
  },
  {
    homepage: 'https://www.cypress.io/',
    repository: 'https://github.com/cypress-io/cypress',
    icon: 'cypress.png',
    keywords: ['cypress'],
    name: 'Cypress',
  },
  {
    homepage: 'https://avajs.dev/',
    repository: 'https://github.com/avajs/ava',
    icon: 'ava.png',
    keywords: ['ava'],
    name: 'AVA',
  },
  {
    homepage: 'https://miragejs.com/',
    repository: 'https://github.com/miragejs',
    icon: 'mirage.png',
    keywords: ['mirage'],
    name: 'Mirage',
  },
  {
    homepage: 'https://markdown-it.github.io/',
    repository: 'https://github.com/markdown-it/markdown-it',
    icon: 'markdown.png',
    keywords: ['markdownit'],
    name: 'MarkdownIt',
    darkInvert: true,
  },
  {
    homepage: 'https://highlightjs.org/',
    repository: 'https://github.com/highlightjs/highlight.js',
    icon: 'hljs.png',
    keywords: ['highlightjs', 'highlight.js', 'hljs'],
    name: 'HighlightJS',
  },
  {
    homepage: 'https://shiki.style/',
    repository: 'https://github.com/shikijs/shiki',
    icon: 'shiki.png',
    keywords: ['shiki', 'highlight'],
    name: 'Shiki',
  },
  {
    homepage: 'http://logic-flow.org/',
    repository: 'https://github.com/didi/LogicFlow',
    icon: 'logic-flow.png',
    keywords: ['logic-flow'],
    name: 'LogicFlow',
  },
  {
    homepage: 'https://threejs.org/',
    repository: 'https://github.com/mrdoob/three.js/',
    icon: 'three.js.png',
    keywords: ['threejs', 'three.js'],
    name: 'ThreeJS',
    darkInvert: true,
    lessRadius: true,
  },
  {
    homepage: 'https://pptr.dev/',
    repository: 'https://github.com/puppeteer/puppeteer',
    icon: 'puppeteer.png',
    keywords: ['pptr', 'puppeteer'],
    name: 'Puppeteer',
  },
  {
    homepage: 'https://yeoman.io/',
    repository: 'https://github.com/yeoman/yo',
    icon: 'yeoman.png',
    keywords: ['yo', 'yeoman'],
    name: 'Yeoman',
  },
  {
    homepage: 'https://socket.io/',
    repository: 'https://github.com/socketio/socket.io',
    icon: 'socket-io.png',
    keywords: ['socketio'],
    name: 'SocketIO',
    darkInvert: true,
  },
  {
    homepage: 'https://sequelize.org/',
    repository: 'https://github.com/sequelize/sequelize',
    icon: 'sequelize.png',
    keywords: ['sequelize', 'orm'],
    name: 'Sequelize',
  },
  {
    homepage: 'https://www.prisma.io/',
    repository: 'https://github.com/prisma/prisma',
    icon: 'prisma.png',
    keywords: ['prisma', 'orm'],
    name: 'Prisma',
    darkInvert: true,
  },
  {
    homepage: 'https://webassembly.org/',
    repository: 'https://github.com/WebAssembly',
    icon: 'webassembly.png',
    keywords: ['WebAssembly'],
    name: 'WebAssembly',
  },
]
