export default <AppItem[]>[
  {
    homepage: 'https://www.google.com/',
    repository: 'https://github.com/google',
    icon: 'google.png',
    keywords: ['google'],
    name: 'Google',
  },
  {
    homepage: 'https://www.microsoft.com/',
    repository: 'https://github.com/microsoft',
    icon: 'microsoft.png',
    keywords: ['microsoft'],
    name: 'Microsoft',
  },
  {
    homepage: 'https://www.apple.com/',
    repository: 'https://github.com/apple',
    icon: 'apple.png',
    keywords: ['apple'],
    name: 'Apple',
    darkInvert: true,
  },
  {
    homepage: 'https://x.com/',
    repository: 'https://github.com/twitter',
    icon: 'x.png',
    keywords: ['x', 'twitter'],
    name: 'X',
    darkInvert: true,
  },
  {
    homepage: 'https://bsky.app',
    icon: 'bsky.png',
    keywords: ['bsky', 'bluesky'],
    name: 'Bluesky',
  },
  {
    homepage: 'https://about.facebook.com/meta',
    repository: 'https://github.com/facebook',
    icon: 'meta.png',
    keywords: ['facebook', 'meta'],
    name: 'Meta',
  },
  {
    homepage: 'https://www.xiaohongshu.com/',
    icon: 'xhs.png',
    keywords: ['小红书', 'xiaohongshu', 'xhs'],
    name: '小红书',
  },
  {
    homepage: 'https://www.youtube.com/',
    repository: 'https://github.com/youtube',
    icon: 'youtube.png',
    keywords: ['youtube'],
    name: 'YouTube',
  },
  {
    homepage: 'https://www.bilibili.com/',
    repository: 'https://github.com/bilibili',
    icon: 'bilibili.png',
    keywords: ['bilibili'],
    name: '哔哩哔哩',
  },
  {
    homepage: 'https://github.com/',
    repository: 'https://github.com/github',
    icon: 'github.png',
    keywords: ['github'],
    name: 'GitHub',
    darkInvert: true,
  },
  {
    homepage: 'https://gitlab.com/',
    repository: 'https://github.com/gitlabhq',
    icon: 'gitlab.png',
    keywords: ['gitlab'],
    name: 'GitLab',
  },
  {
    homepage: 'https://gitee.com/',
    icon: 'gitee.png',
    keywords: ['gitee'],
    name: 'Gitee',
  },
  {
    homepage: 'https://git-scm.com/',
    repository: 'https://github.com/git/git',
    icon: 'git.png',
    keywords: ['git'],
    name: 'Git',
  },
  {
    homepage: 'https://www.npmjs.com/',
    repository: 'https://github.com/npm',
    icon: 'npm.png',
    keywords: ['npm'],
    name: 'NPM',
  },
  {
    homepage: 'https://yarnpkg.com/',
    repository: 'https://github.com/yarnpkg/berry',
    icon: 'yarn.png',
    keywords: ['yarn'],
    name: 'Yarn',
  },
  {
    homepage: 'https://pnpm.io/',
    repository: 'https://github.com/pnpm/pnpm',
    icon: 'pnpm.png',
    keywords: ['pnpm'],
    name: 'PNPM',
  },
  {
    homepage: 'https://bower.io/',
    repository: 'https://github.com/bower/bower',
    icon: 'bower.png',
    keywords: ['bower'],
    name: 'Bower',
  },
  {
    homepage: 'https://www.jsdelivr.com/',
    repository: 'https://github.com/jsdelivr/jsdelivr',
    icon: 'jsdelivr.png',
    keywords: ['jsdelivr', 'cdn'],
    name: 'JSDelivr',
  },
  {
    homepage: 'https://cdnjs.com/',
    repository: 'https://github.com/cdnjs/cdnjs',
    icon: 'cdnjs.png',
    keywords: ['cdnjs', 'cdn'],
    name: 'CDNJS',
  },
  {
    homepage: 'https://unpkg.com/',
    repository: 'https://github.com/mjackson/unpkg',
    icon: 'unpkg.png',
    keywords: ['unpkg', 'cdn'],
    name: 'UNPKG',
    darkInvert: true,
  },
  {
    homepage: 'https://esm.sh/',
    repository: 'https://github.com/ije/esm.sh',
    icon: 'esm-cdn.png',
    keywords: ['esm', 'cdn'],
    name: 'ESM',
    darkInvert: true,
  },
  {
    homepage: 'https://www.skypack.dev/',
    repository: 'https://github.com/skypackjs',
    icon: 'skypack.png',
    keywords: ['skypack', 'cdn'],
    name: 'Skypack',
  },
  {
    homepage: 'https://www.bootcdn.cn/',
    icon: 'bootcdn.png',
    keywords: ['bootcdn', 'cdn'],
    name: 'BootCDN',
  },
  {
    homepage: 'https://developer.mozilla.org/',
    repository: 'https://github.com/mdn',
    icon: 'mdn.png',
    keywords: ['mdn'],
    name: 'MDN',
  },
  {
    homepage: 'https://developer.chrome.com/',
    icon: 'chrome.png',
    keywords: ['chromefordevelopers'],
    name: 'Developers',
  },
  {
    homepage: 'https://web.dev/',
    icon: 'webdev.png',
    keywords: ['web dev'],
    name: 'web.dev',
  },
  {
    homepage: 'https://javascript.info/',
    repository: 'https://github.com/javascript-tutorial',
    icon: 'javascript-tutorial.png',
    keywords: ['javascript-tutorial', 'js'],
    name: 'JSTutorial',
  },
  {
    homepage: 'https://stackoverflow.com/',
    icon: 'stackoverflow.png',
    keywords: ['stack overflow'],
    name: 'StackOverflow',
  },
  {
    homepage: 'https://caniuse.com/',
    repository: 'https://github.com/fyrd/caniuse',
    icon: 'caniuse.png',
    keywords: ['caniuse'],
    name: 'Can I use',
  },
  {
    homepage: 'https://regexr.com/',
    repository: 'https://github.com/gskinner/regexr',
    icon: 'regexr.png',
    keywords: ['regexr'],
    name: 'RegExr',
  },
  {
    homepage: 'https://regex101.com/',
    icon: 'regex101.png',
    keywords: ['regex101'],
    name: 'Regex101',
  },
  {
    homepage: 'https://travis-ci.org/',
    repository: 'https://github.com/travis-ci',
    icon: 'travis.png',
    keywords: ['travis', 'ci'],
    name: 'Travis',
  },
  {
    homepage: 'https://www.jenkins.io/',
    repository: 'https://github.com/jenkinsci',
    icon: 'jenkins.png',
    keywords: ['jenkins', 'ci'],
    name: 'Jenkins',
  },
  {
    homepage: 'https://code.visualstudio.com/',
    repository: 'https://github.com/microsoft/vscode',
    icon: 'vscode.png',
    keywords: ['vscode', 'visualstudio-code'],
    name: 'VSCode',
  },
  {
    homepage: 'https://www.cursor.com/',
    repository: 'https://github.com/getcursor/cursor',
    icon: 'cursor.png',
    keywords: ['cursor'],
    name: 'Cursor',
    darkInvert: true,
  },
  {
    homepage: 'https://windsurf.com/',
    icon: 'windsurf.png',
    keywords: ['windsurf'],
    name: 'Windsurf',
    darkInvert: true,
  },
  {
    homepage: 'https://www.trae.cn/',
    repository: 'https://github.com/Trae-AI',
    icon: 'trae.png',
    keywords: ['trae'],
    name: 'Trae',
  },
  {
    homepage: 'https://kiro.dev/',
    repository: 'https://github.com/kirodotdev/Kiro',
    icon: 'kiro.png',
    keywords: ['kiro'],
    name: 'Kiro',
  },
  {
    homepage: 'https://www.jetbrains.com/webstorm/',
    icon: 'webstorm.png',
    keywords: ['webstorm'],
    name: 'WebStorm',
  },
  {
    homepage: 'https://zed.dev/',
    repository: 'https://github.com/zed-industries/zed',
    icon: 'zed.png',
    keywords: ['zed'],
    name: 'Zed',
    lessRadius: true,
  },
  {
    homepage: 'http://www.sublimetext.com/',
    icon: 'sublimetext.png',
    keywords: ['sublimetext'],
    name: 'SublimeText',
  },
  {
    homepage: 'https://vercel.com/',
    repository: 'https://github.com/vercel/vercel',
    icon: 'vercel.png',
    keywords: ['vercel'],
    name: 'Vercel',
    darkInvert: true,
    lessRadius: true,
  },
  {
    homepage: 'https://app.netlify.com/',
    repository: 'https://github.com/netlify',
    icon: 'netlify.png',
    keywords: ['netlify'],
    name: 'Netlify',
  },
  {
    homepage: 'https://www.cloudflare.com/',
    repository: 'https://github.com/cloudflare',
    icon: 'cloudflare.png',
    keywords: ['cloudflare'],
    name: 'Cloudflare',
  },
  {
    homepage: 'https://github.com/superfly/',
    repository: 'https://github.com/superfly/',
    icon: 'flyio.png',
    keywords: ['fly.io'],
    name: 'Fly.io',
  },
  {
    homepage: 'https://deno.com/deploy/',
    repository: 'https://github.com/denoland',
    icon: 'denodeploy.png',
    iconDark: 'denodeploy_dark.png',
    keywords: ['denodeploy'],
    name: 'Deno Deploy',
  },
  {
    homepage: 'https://zeabur.com/',
    repository: 'https://github.com/zeabur/zeabur',
    icon: 'zeabur.png',
    keywords: ['zeabur'],
    name: 'Zeabur',
    lessRadius: true,
  },
  {
    homepage: 'https://render.com/',
    repository: 'https://github.com/renderinc',
    icon: 'render.png',
    keywords: ['render'],
    name: 'Render',
    lessRadius: true,
    darkInvert: true,
  },
  {
    homepage: 'https://firebase.google.com/',
    repository: 'https://github.com/firebase/',
    icon: 'firebase.png',
    keywords: ['firebase'],
    name: 'Firebase',
  },
  {
    homepage: 'https://supabase.com/',
    repository: 'https://github.com/supabase/supabase',
    icon: 'supabase.png',
    keywords: ['supabase'],
    name: 'Supabase',
  },
  {
    homepage: 'https://neon.tech/',
    repository: 'https://github.com/neondatabase/neon',
    icon: 'neon.png',
    keywords: ['neon'],
    name: 'Neon',
  },
  {
    homepage: 'https://xata.io/',
    repository: 'https://github.com/xataio/',
    icon: 'xata.png',
    keywords: ['xata'],
    name: 'Xata',
  },
  {
    homepage: 'https://tembo.io/',
    repository: 'https://github.com/tembo-io/tembo',
    icon: 'tembo.png',
    keywords: ['tembo'],
    name: 'Tembo',
  },
  {
    homepage: 'https://turso.tech/drizzle',
    repository: 'https://github.com/tursodatabase',
    icon: 'turso.png',
    keywords: ['turso'],
    name: 'Turso',
  },
  {
    homepage: 'https://sqlitecloud.io/',
    repository: 'https://github.com/sqlitecloud',
    icon: 'sqlitecloud.png',
    keywords: ['sqlitecloud'],
    name: 'SQLite Cloud',
  },
  {
    homepage: 'https://www.singlestore.com/',
    repository: 'https://github.com/singlestore-labs/',
    icon: 'singlestore.png',
    keywords: ['singlestore'],
    name: 'SingleStore',
    darkInvert: true,
  },
  {
    homepage: 'https://planetscale.com/',
    repository: 'https://github.com/planetscale',
    icon: 'planetscale.png',
    keywords: ['planetscale'],
    name: 'PlanetScale',
    darkInvert: true,
  },
  {
    homepage: 'https://stackblitz.com/',
    repository: 'https://github.com/stackblitz/core',
    icon: 'stackblitz.png',
    keywords: ['stackblitz'],
    name: 'StackBlitz',
  },
  {
    homepage: 'https://codesandbox.io/',
    repository: 'https://github.com/codesandbox/codesandbox-client',
    icon: 'codesandbox.png',
    keywords: ['codesandbox'],
    name: 'CodeSandbox',
    darkInvert: true,
  },
  {
    homepage: 'https://github.com/jsfiddle',
    repository: 'https://jsfiddle.net/',
    icon: 'js-fiddle.png',
    keywords: ['js-fiddle'],
    name: 'JSFiddle',
  },
  {
    homepage: 'https://codepen.io/',
    icon: 'codepen.png',
    keywords: ['codepen'],
    name: 'CodePen',
    darkInvert: true,
  },
  {
    homepage: 'https://tinypng.com/',
    repository: 'https://github.com/tinify',
    icon: 'tinypng.png',
    keywords: ['tinypng'],
    name: 'TinyPNG',
  },
  {
    homepage: 'https://dev.to/',
    icon: 'devto.png',
    keywords: ['dev'],
    name: 'DEV',
    darkInvert: true,
  },
  {
    homepage: 'https://medium.com/',
    repository: 'https://github.com/Medium',
    icon: 'medium.png',
    keywords: ['medium'],
    name: 'Medium',
    darkInvert: true,
  },
  {
    homepage: 'https://css-tricks.com/',
    icon: 'css-tricks.png',
    keywords: ['css-tricks'],
    name: 'CSS Tricks',
  },
  {
    homepage: 'https://www.smashingmagazine.com/',
    icon: 'smashing-magazine.png',
    keywords: ['smashing-magazine'],
    name: 'SmashingMagazine',
  },
  {
    homepage: 'https://www.producthunt.com/',
    repository: 'https://github.com/producthunt',
    icon: 'producthunt.png',
    keywords: ['producthunt'],
    name: 'Product Hunt',
  },
  {
    homepage: 'https://www.yuque.com/',
    repository: 'https://github.com/yuque',
    icon: 'yuque.png',
    keywords: ['语雀', 'yuque'],
    name: '语雀',
  },
  {
    homepage: 'https://www.feishu.cn/',
    icon: 'feishu.png',
    keywords: ['飞书', 'feishu'],
    name: '飞书',
  },
  {
    homepage: 'https://www.zhihu.com/',
    repository: 'https://github.com/zhihu',
    icon: 'zhihu.png',
    keywords: ['知乎', 'zhihu'],
    name: '知乎',
  },
  {
    homepage: 'https://juejin.im/',
    repository: 'https://github.com/xitu',
    icon: 'juejin.png',
    keywords: ['掘金', 'juejin'],
    name: '掘金',
  },
  {
    homepage: 'https://segmentfault.com/',
    icon: 'sf.png',
    keywords: ['segmentfault', 'sf', '思否', 'sifou'],
    name: '思否',
  },
]
