export default<AppItem[]> [{
  homepage: 'https://element.eleme.io/',
  repository: 'https://github.com/ElemeFE/element',
  icon: 'element-ui.png',
  keywords: ['饿了么', 'element-ui', 'vue', 'ui'],
  name: 'Element',
}, {
  homepage: 'https://element-plus.org/',
  repository: 'https://github.com/element-plus/element-plus',
  icon: 'element-plus.png',
  keywords: ['饿了么', 'element-plus', 'vue3', 'ui'],
  name: 'ElementPlus',
}, {
  homepage: 'http://v4.iviewui.com/',
  repository: 'https://github.com/view-design/ViewUI',
  icon: 'iview.png',
  keywords: ['iview-ui', 'vue', 'ui'],
  name: 'View UI',
}, {
  homepage: 'https://www.iviewui.com/',
  repository: 'https://github.com/view-design/ViewUIPlus',
  icon: 'iview.png',
  keywords: ['iview-ui-plus', 'vue3', 'ui'],
  name: 'View UI Plus',
}, {
  homepage: 'https://vuetifyjs.com/',
  repository: 'https://github.com/vuetifyjs/vuetify',
  icon: 'vuetify.png',
  keywords: ['vuetify', 'vue', 'ui'],
  name: 'Vuetify',
}, {
  homepage: 'https://quasar.dev/',
  repository: 'https://github.com/quasarframework/quasar',
  icon: 'quasar.png',
  keywords: ['quasar', 'vue', 'ui'],
  name: 'Quasar',
}, {
  homepage: 'https://www.antdv.com/',
  repository: 'https://github.com/vueComponent/ant-design-vue',
  icon: 'ant-design-vue.png',
  keywords: ['ant-design-vue', 'antdvue', 'ui'],
  name: 'Antd Vue',
}, {
  homepage: 'https://www.naiveui.com/',
  repository: 'https://github.com/tusen-ai/naive-ui',
  icon: 'naiveui.png',
  keywords: ['naiveui', 'vue', 'ui'],
  name: 'Naive UI',
}, {
  homepage: 'https://tdesign.tencent.com/',
  repository: 'https://github.com/Tencent/tdesign',
  icon: 'tdesign.png',
  keywords: ['tdesign', 'vue', 'react', 'flutter', 'angular', 'mobile', 'ui'],
  name: 'TDesign',
}, {
  homepage: 'https://arco.design/',
  repository: 'https://github.com/arco-design',
  icon: 'arco-design.png',
  keywords: ['arco-design', 'vue', 'react', 'ui'],
  name: 'Arco Design',
}, {
  homepage: 'https://muse-ui.org/',
  repository: 'https://github.com/museui/muse-ui',
  icon: 'museui.png',
  keywords: ['museui', 'vue', 'ui'],
  name: 'Muse UI',
}, {
  homepage: 'https://vusion.github.io/cloud-ui/',
  repository: 'https://github.com/vusion/cloud-ui',
  icon: 'vusion.png',
  keywords: ['cloud-ui', 'vue', 'ui'],
  name: 'Cloud UI',
}, {
  homepage: 'https://youzan.github.io/vant/',
  repository: 'https://github.com/youzan/vant',
  icon: 'vant.png',
  keywords: ['vant', 'vue', 'mobile', 'ui'],
  name: 'Vant',
}, {
  homepage: 'https://didi.github.io/cube-ui/',
  repository: 'https://github.com/didi/cube-ui',
  icon: 'cube.png',
  keywords: ['cube', 'vue', 'mobile', 'ui'],
  name: 'Cube UI',
}, {
  homepage: 'https://nutui.jd.com/#/',
  repository: 'https://github.com/jdf2e/nutui',
  icon: 'nutui.png',
  keywords: ['nutui', 'vue', '小程序', 'mobile', 'ui'],
  name: 'Nut UI',
}, {
  homepage: 'https://varlet-varletjs.vercel.app/',
  repository: 'https://github.com/varletjs/varlet',
  icon: 'varlet.png',
  keywords: ['varlet', 'vue3', 'mobile', 'ui'],
  name: 'Varlet',
}, {
  homepage: 'https://weui.io/',
  repository: 'https://github.com/Tencent/weui',
  icon: 'weui.png',
  keywords: ['weui', 'mobile', '小程序', 'ui'],
  name: 'We UI',
}, {
  homepage: 'https://vux.li/',
  repository: 'https://github.com/airyland/vux',
  icon: 'vux.png',
  keywords: ['vux', 'vue', 'mobile', 'ui'],
  name: 'VUX',
}, {
  homepage: 'https://at-ui.github.io/at-ui/',
  repository: 'https://github.com/at-ui/at-ui',
  icon: 'at-ui.png',
  keywords: ['atui', 'vue', 'ui'],
  name: 'At UI',
}, {
  homepage: 'https://ant.design/',
  repository: 'https://github.com/ant-design/ant-design/',
  icon: 'ant-design.png',
  keywords: ['ant-design', 'react', 'ui'],
  name: 'Ant Design',
}, {
  homepage: 'https://material-ui.com/',
  repository: 'https://github.com/mui/material-ui',
  icon: 'material-ui.png',
  keywords: ['materialui', 'react', 'ui'],
  name: 'Material UI',
}, {
  homepage: 'https://chakra-ui.com/',
  repository: 'https://github.com/chakra-ui/chakra-ui',
  icon: 'chakra.png',
  keywords: ['chakraui', 'react', 'ui'],
  name: 'Chakra UI',
}, {
  homepage: 'https://ui.shadcn.com/',
  repository: 'https://github.com/shadcn/ui',
  icon: 'shadcnui.png',
  keywords: ['shadcnui', 'react', 'ui'],
  name: 'Shadcn UI',
}, {
  homepage: 'https://www.radix-ui.com/',
  repository: 'https://github.com/radix-ui',
  icon: 'radixui.png',
  keywords: ['radix', 'react', 'ui'],
  name: 'Radix UI',
}, {
  homepage: 'https://semi.design/',
  repository: 'https://github.com/DouyinFE/semi-design',
  icon: 'semi.png',
  keywords: ['semidesign', 'react', 'ui'],
  name: 'Semi Design',
  darkInvert: true,
}, {
  homepage: 'https://rsuitejs.com/',
  repository: 'https://github.com/rsuite/rsuite',
  icon: 'rsuite.png',
  keywords: ['rsuite', 'react suite', 'ui'],
  name: 'React Suite',
}, {
  homepage: 'https://taro-ui.jd.com/',
  repository: 'https://github.com/NervJS/taro-ui',
  icon: 'taro.png',
  keywords: ['taro', 'react', '小程序', 'ui', 'mobile'],
  name: 'Taro UI',
}, {
  homepage: 'https://nsfi.github.io/ppfish-components/',
  repository: 'https://github.com/NSFI/ppfish-components',
  icon: 'fish.png',
  keywords: ['fish', 'react', 'mobile', 'ui'],
  name: 'Fish Design',
}, {
  homepage: 'https://ossa.miaode.com/',
  repository: 'https://github.com/NeteaseYanxuan/OSSA',
  icon: 'ossa.png',
  keywords: ['ossa', 'react', 'mobile', 'ui'],
  name: 'OSSA',
}, {
  homepage: 'https://ng-alain.com/zh',
  repository: 'https://github.com/ng-alain/ng-alain/',
  icon: 'ng-alain.png',
  keywords: ['angular', 'ui', 'ngalain'],
  name: 'NG Alain',
}, {
  homepage: 'https://ng.ant.design',
  repository: 'https://github.com/NG-ZORRO/ng-zorro-antd',
  icon: 'zorro.png',
  keywords: ['angular', 'ui', 'ng-zorro-antd'],
  name: 'NG Zorro',
}, {
  homepage: 'https://getbootstrap.com/',
  repository: 'https://github.com/twbs/bootstrap',
  icon: 'bootstrap.png',
  keywords: ['bootstrap', 'ui'],
  name: 'Bootstrap',
}, {
  homepage: 'https://l-ui.com/',
  repository: 'https://github.com/yued-fe/lulu',
  icon: 'luluui.png',
  keywords: ['luluui'],
  name: 'LuLu UI',
}, {
  homepage: 'https://headlessui.com/',
  repository: 'https://github.com/tailwindlabs/headlessui',
  icon: 'headlessui.png',
  keywords: ['headlessui', 'vue', 'react', 'ui'],
  name: 'Headless UI',
}, {
  homepage: 'https://storybook.js.org/',
  repository: 'https://github.com/storybookjs/storybook',
  icon: 'storybook.png',
  keywords: ['storybook'],
  name: 'Storybook',
}, {
  homepage: 'https://flutter-go.pub/',
  repository: 'https://github.com/alibaba/flutter-go/',
  icon: 'flutter-go.png',
  keywords: ['fluttergo'],
  name: 'Flutter Go',
}, {
  homepage: 'https://echarts.apache.org/',
  repository: 'https://github.com/apache/echarts',
  icon: 'echarts.png',
  keywords: ['echarts'],
  name: 'ECharts',
}, {
  homepage: 'https://antv.alipay.com/',
  repository: 'https://github.com/antvis/',
  icon: 'antv.png',
  keywords: ['antv', 'charts'],
  name: 'AntV',
}, {
  homepage: 'http://www.iconfont.cn/',
  icon: 'iconfont.png',
  keywords: ['iconfont'],
  name: 'IconFont',
}, {
  homepage: 'https://fonts.google.com/',
  icon: 'google-fonts.png',
  keywords: ['google-fonts'],
  name: 'GoogleFonts',
}, {
  homepage: 'https://www.flaticon.com/',
  icon: 'flaticon.png',
  keywords: ['flaticon'],
  name: 'Flaticon',
}, {
  homepage: 'https://www.iconfinder.com/',
  icon: 'iconfinder.png',
  keywords: ['iconfinder'],
  name: 'Iconfinder',
  darkInvert: true,
}, {
  homepage: 'https://useanimations.com/',
  icon: 'useanimations.png',
  keywords: ['useanimations'],
  name: 'UseAnimations',
}, {
  homepage: 'https://feathericons.com/',
  repository: 'https://github.com/feathericons/feather',
  icon: 'feather.png',
  keywords: ['feathericons'],
  name: 'Feather',
}, {
  homepage: 'https://heroicons.com/',
  repository: 'https://github.com/tailwindlabs/heroicons',
  icon: 'heroicons.png',
  keywords: ['heroicons'],
  name: 'Heroicons',
}, {
  homepage: 'http://iconpark.bytedance.com/',
  repository: 'https://github.com/bytedance/iconpark',
  icon: 'iconpark.png',
  keywords: ['iconpark'],
  name: 'IconPark',
}, {
  homepage: 'https://remixicon.com/',
  repository: 'https://github.com/Remix-Design/RemixIcon',
  icon: 'remixicon.png',
  keywords: ['remixicon'],
  name: 'RemixIcon',
}, {
  homepage: 'https://tabler.io/icons',
  repository: 'https://github.com/tabler/tabler',
  icon: 'tabler.png',
  keywords: ['tablericons'],
  name: 'TablerIcons',
}, {
  homepage: 'https://icones.js.org/',
  repository: 'https://github.com/antfu/icones',
  icon: 'icones.png',
  keywords: ['icones', 'icônes'],
  name: 'Icônes',
  darkInvert: true,
}, {
  homepage: 'https://smashicons.com/',
  repository: 'https://github.com/Smashicons',
  icon: 'smashicons.png',
  keywords: ['smashicons'],
  name: 'Smashicons',
}, {
  homepage: 'https://www.figma.com/',
  repository: 'https://github.com/figma',
  icon: 'figma.png',
  keywords: ['figma'],
  name: 'Figma',
}, {
  homepage: 'https://dribbble.com/',
  repository: 'https://github.com/dribbble',
  icon: 'dribbble.png',
  keywords: ['dribbble'],
  name: 'Dribbble',
}, {
  homepage: 'https://www.pinterest.com/',
  repository: 'https://github.com/pinterest',
  icon: 'pinterest.png',
  keywords: ['pinterest'],
  name: 'Pinterest',
}, {
  homepage: 'https://www.behance.net/',
  repository: 'https://github.com/behance',
  icon: 'behance.png',
  keywords: ['behance'],
  name: 'Behance',
}, {
  homepage: 'https://craftwork.design/',
  icon: 'craftwork.png',
  keywords: ['craftwork'],
  name: 'Craftwork',
}, {
  homepage: 'https://discover.gumroad.com/',
  repository: 'https://github.com/gumroad',
  icon: 'gumroad.png',
  keywords: ['gumroad'],
  name: 'Gumroad',
}, {
  homepage: 'https://www.ui8.net/',
  icon: 'ui8.png',
  keywords: ['ui8'],
  name: 'UI8',
}]
