import {
  requireImg,
} from '../utils'

const apps: AppItem[] = [{
  url: 'https://element.eleme.io/',
  githubUrl: 'https://github.com/ElemeFE/element',
  imgSrc: requireImg('element-ui.png'),
  keyWords: ['饿了么', 'element-ui', 'vue', 'ui'],
  label: 'Element UI',
}, {
  url: 'https://element-plus.org/',
  githubUrl: 'https://github.com/element-plus/element-plus',
  imgSrc: requireImg('element-plus.png'),
  keyWords: ['饿了么', 'element-plus', 'vue3', 'ui'],
  label: 'ElementPlus',
}, {
  url: 'http://v4.iviewui.com/',
  githubUrl: 'https://github.com/view-design/ViewUI',
  imgSrc: requireImg('iview.png'),
  keyWords: ['iview-ui', 'vue'],
  label: 'View UI',
}, {
  url: 'https://www.iviewui.com/',
  githubUrl: 'https://github.com/view-design/ViewUIPlus',
  imgSrc: requireImg('iview.png'),
  keyWords: ['iview-ui-plus', 'vue3'],
  label: 'View UI Plus',
}, {
  url: 'https://vuetifyjs.com/',
  githubUrl: 'https://github.com/vuetifyjs/vuetify',
  imgSrc: requireImg('vuetify.png'),
  keyWords: ['vuetify', 'vue', 'ui'],
  label: 'Vuetify',
}, {
  url: 'https://quasar.dev/',
  githubUrl: 'https://github.com/quasarframework/quasar',
  imgSrc: requireImg('quasar.png'),
  keyWords: ['quasar', 'vue', 'ui'],
  label: 'Quasar',
}, {
  url: 'https://www.antdv.com/',
  githubUrl: 'https://github.com/vueComponent/ant-design-vue',
  imgSrc: requireImg('ant-design-vue.png'),
  keyWords: ['ant-design-vue', 'antdvue', 'ui'],
  label: 'Antd Vue',
}, {
  url: 'https://www.naiveui.com/',
  githubUrl: 'https://github.com/TuSimple/naive-ui',
  imgSrc: requireImg('naiveui.png'),
  keyWords: ['naiveui', 'vue'],
  label: 'Naive UI',
}, {
  url: 'https://tdesign.tencent.com/',
  githubUrl: 'https://github.com/Tencent/tdesign',
  imgSrc: requireImg('tdesign.png'),
  keyWords: ['tdesign', 'vue', 'react', 'flutter', 'angular', 'mobile', 'ui'],
  label: 'TDesign',
}, {
  url: 'https://arco.design/',
  githubUrl: 'https://github.com/arco-design',
  imgSrc: requireImg('arco-design.png'),
  keyWords: ['arco-design', 'vue', 'react', 'ui'],
  label: 'Arco Design',
}, {
  url: 'https://muse-ui.org/',
  githubUrl: 'https://github.com/museui/muse-ui',
  imgSrc: requireImg('museui.png'),
  keyWords: ['museui', 'vue', 'ui'],
  label: 'Muse UI',
}, {
  url: 'https://youzan.github.io/vant/',
  githubUrl: 'https://github.com/youzan/vant',
  imgSrc: requireImg('vant.png'),
  keyWords: ['vant', 'vue', 'mobile', 'ui'],
  label: 'Vant',
}, {
  url: 'https://didi.github.io/cube-ui/',
  githubUrl: 'https://github.com/didi/cube-ui',
  imgSrc: requireImg('cube.png'),
  keyWords: ['cube', 'vue', 'mobile', 'ui'],
  label: 'Cube UI',
}, {
  url: 'https://nutui.jd.com/#/',
  githubUrl: 'https://github.com/jdf2e/nutui',
  imgSrc: requireImg('nutui.png'),
  keyWords: ['nutui', 'vue', '小程序', 'mobile', 'ui'],
  label: 'Nut UI',
}, {
  url: 'https://varlet-varletjs.vercel.app/',
  githubUrl: 'https://github.com/varletjs/varlet',
  imgSrc: requireImg('varlet.png'),
  keyWords: ['varlet', 'vue3', 'mobile', 'ui'],
  label: 'Varlet',
}, {
  url: 'https://vux.li/',
  githubUrl: 'https://github.com/airyland/vux',
  imgSrc: requireImg('vux.png'),
  keyWords: ['vux', 'vue', 'mobile', 'ui'],
  label: 'VUX',
  darkInvert: true,
}, {
  url: 'https://at-ui.github.io/at-ui/',
  githubUrl: 'https://github.com/at-ui/at-ui',
  imgSrc: requireImg('at-ui.png'),
  keyWords: ['atui', 'vue'],
  label: 'At UI',
}, {
  url: 'https://ant.design/',
  githubUrl: 'https://github.com/ant-design/ant-design/',
  imgSrc: requireImg('ant-design.png'),
  keyWords: ['ant-design', 'react', 'ui'],
  label: 'Ant Design',
}, {
  url: 'https://material-ui.com/',
  githubUrl: 'https://github.com/mui-org/material-ui',
  imgSrc: requireImg('material-ui.png'),
  keyWords: ['materialui', 'react'],
  label: 'Material UI',
}, {
  url: 'https://semi.design/',
  githubUrl: 'https://github.com/DouyinFE/semi-design',
  imgSrc: requireImg('semi.png'),
  keyWords: ['semi', 'react', 'ui'],
  label: 'Semi Design',
  darkInvert: true,
}, {
  url: 'https://rsuitejs.com/',
  githubUrl: 'https://github.com/rsuite/rsuite',
  imgSrc: requireImg('rsuite.png'),
  keyWords: ['rsuite', 'react suite', 'ui'],
  label: 'React Suite',
}, {
  url: 'https://taro-ui.jd.com/',
  githubUrl: 'https://github.com/NervJS/taro-ui',
  imgSrc: requireImg('taro.png'),
  keyWords: ['taro', 'react', '小程序', 'ui', 'mobile'],
  label: 'Taro UI',
}, {
  url: 'https://ng-alain.com/zh',
  githubUrl: 'https://github.com/ng-alain/ng-alain/',
  imgSrc: requireImg('ng-alain.png'),
  keyWords: ['angular', 'ui', 'ngalain'],
  label: 'NG Alain',
}, {
  url: 'https://ng.ant.design',
  githubUrl: 'https://github.com/NG-ZORRO/ng-zorro-antd',
  imgSrc: requireImg('zorro.png'),
  keyWords: ['angular', 'ui', 'ng-zorro-antd'],
  label: 'NG Zorro',
}, {
  url: 'https://getbootstrap.com/',
  githubUrl: 'https://github.com/twbs/bootstrap',
  imgSrc: requireImg('bootstrap.png'),
  keyWords: ['bootstrap', 'ui'],
  label: 'Bootstrap',
}, {
  url: 'https://l-ui.com/',
  githubUrl: 'https://github.com/yued-fe/lulu',
  imgSrc: requireImg('luluui.png'),
  keyWords: ['luluui'],
  label: 'LuLu UI',
}, {
  url: 'https://flutter-go.pub/',
  githubUrl: 'https://github.com/alibaba/flutter-go/',
  imgSrc: requireImg('flutter-go.png'),
  keyWords: ['fluttergo'],
  label: 'Flutter Go',
}, {
  url: 'https://echarts.apache.org/',
  githubUrl: 'https://github.com/apache/incubator-echarts',
  imgSrc: requireImg('echarts.png'),
  keyWords: ['echarts'],
  label: 'ECharts',
}, {
  url: 'https://antv.alipay.com/',
  githubUrl: 'https://github.com/antvis/',
  imgSrc: requireImg('antv.png'),
  keyWords: ['antv', 'charts'],
  label: 'AntV',
}, {
  url: 'https://dribbble.com/',
  imgSrc: requireImg('dribbble.png'),
  keyWords: ['dribbble'],
  label: 'Dribbble',
}, {
  url: 'http://www.iconfont.cn/',
  imgSrc: requireImg('iconfont.png'),
  keyWords: ['iconfont'],
  label: 'IconFont',
}, {
  url: 'https://fonts.google.com/',
  imgSrc: requireImg('google-fonts.png'),
  keyWords: ['google-fonts'],
  label: 'GoogleFonts',
}, {
  url: 'https://www.flaticon.com/',
  imgSrc: requireImg('flaticon.png'),
  keyWords: ['flaticon'],
  label: 'Flaticon',
}, {
  url: 'https://www.iconfinder.com/',
  imgSrc: requireImg('iconfinder.png'),
  keyWords: ['iconfinder'],
  label: 'Iconfinder',
  darkInvert: true,
}, {
  url: 'https://useanimations.com/',
  imgSrc: requireImg('useanimations.png'),
  keyWords: ['useanimations'],
  label: 'UseAnimations',
}, {
  url: 'https://remixicon.com/',
  githubUrl: 'https://github.com/Remix-Design/RemixIcon',
  imgSrc: requireImg('remixicon.png'),
  keyWords: ['remixicon'],
  label: 'RemixIcon',
}, {
  url: 'https://feathericons.com/',
  githubUrl: 'https://github.com/feathericons/feather',
  imgSrc: requireImg('feather.png'),
  keyWords: ['feathericons'],
  label: 'Feather',
}, {
  url: 'https://heroicons.com/',
  githubUrl: 'https://github.com/tailwindlabs/heroicons',
  imgSrc: requireImg('heroicons.png'),
  keyWords: ['heroicons'],
  label: 'Heroicons',
}, {
  url: 'http://iconpark.bytedance.com/',
  githubUrl: 'https://github.com/bytedance/iconpark',
  imgSrc: requireImg('iconpark.png'),
  keyWords: ['iconpark'],
  label: 'IconPark',
}]

export default apps
