export default <AppItem[]>[
  {
    homepage: 'https://pugjs.org/',
    repository: 'https://github.com/pugjs/pug',
    icon: 'pug.png',
    keywords: ['pug', 'html'],
    name: 'Pug',
  },
  {
    homepage: 'https://jade-lang.com/',
    icon: 'jade.png',
    keywords: ['jade', 'html'],
    name: 'Jade',
  },
  {
    homepage: 'https://posthtml.org/',
    repository: 'https://github.com/posthtml/posthtml',
    icon: 'post-html.png',
    keywords: ['PostHTML'],
    name: 'PostHTML',
  },
  {
    homepage: 'https://htmx.org/',
    repository: 'https://github.com/bigskysoftware/htmx',
    icon: 'htmx.png',
    keywords: ['htmx', 'html'],
    name: 'htmx',
  },
  {
    homepage: 'http://sass-lang.com/',
    repository: 'https://github.com/sass/sass',
    icon: 'sass.png',
    keywords: ['sass', 'css'],
    name: 'Sass',
  },
  {
    homepage: 'http://lesscss.org/',
    repository: 'https://github.com/less/less.js',
    icon: 'less.png',
    keywords: ['less', 'css'],
    name: 'Less',
  },
  {
    homepage: 'http://stylus-lang.com/',
    repository: 'https://github.com/stylus/stylus/',
    icon: 'stylus.png',
    keywords: ['stylus', 'css'],
    name: 'Stylus',
    darkInvert: true,
  },
  {
    homepage: 'https://postcss.org/',
    repository: 'https://github.com/postcss/postcss',
    icon: 'postcss.png',
    keywords: ['postcss', 'css'],
    name: 'Postcss',
  },
  {
    homepage: 'https://tailwindcss.com/',
    repository: 'https://github.com/tailwindlabs/tailwindcss',
    icon: 'tailwindcss.png',
    keywords: ['tailwindcss', 'css'],
    name: 'TailwindCSS',
  },
  {
    homepage: 'https://unocss.dev/',
    repository: 'https://github.com/unocss/unocss',
    icon: 'unocss.png',
    keywords: ['unocss'],
    name: 'UnoCSS',
  },
  {
    homepage: 'https://uicolors.app/',
    icon: 'uicolors.png',
    keywords: ['uicolors', 'css'],
    name: 'uicolors',
  },
  {
    homepage: 'https://goober.rocks/',
    repository: 'https://github.com/cristianbote/goober',
    icon: 'goober.png',
    keywords: ['goober', 'css'],
    name: 'Goober',
  },
  {
    homepage: 'https://purgecss.com/',
    repository: 'https://github.com/FullHuman/purgecss',
    icon: 'purgecss.png',
    keywords: ['purgecss', 'css'],
    name: 'PurgeCSS',
    darkInvert: true,
  },
  {
    homepage: 'https://github.com/css-modules/css-modules',
    repository: 'https://github.com/css-modules/css-modules',
    icon: 'css-modules.png',
    keywords: ['css-modules', 'css'],
    name: 'CSS Modules',
    darkInvert: true,
  },
  {
    homepage: 'https://cssinjs.org/',
    repository: 'https://github.com/cssinjs/jss',
    icon: 'jss.png',
    keywords: ['jss', 'css'],
    name: 'JSS',
    lessRadius: true,
  },
  {
    homepage: 'https://emotion.sh/',
    repository: 'https://github.com/emotion-js/emotion',
    icon: 'emotion.png',
    keywords: ['emotion', 'css'],
    name: 'Emotion',
  },
  {
    homepage: 'https://styled-components.com/',
    repository: 'https://github.com/styled-components/styled-components',
    icon: 'styled-components.png',
    keywords: ['styled-components', 'css'],
    name: 'StyledComponents',
  },
  {
    homepage: 'https://vanilla-extract.style/',
    repository: 'https://github.com/vanilla-extract-css/vanilla-extract',
    icon: 'vanilla-extract-style.png',
    keywords: ['vanilla-extract', 'css'],
    name: 'VanillaExtract',
  },
  {
    homepage: 'https://panda-css.com/',
    repository: 'https://github.com/chakra-ui/panda',
    icon: 'panda-css.png',
    keywords: ['panda-css'],
    name: 'panda-css',
  },
  {
    homepage: 'https://open-props.style/',
    repository: 'https://github.com/argyleink/open-props',
    icon: 'open-props.png',
    keywords: ['open-props'],
    name: 'Open Props',
  },
  {
    homepage: 'https://stylexjs.com/',
    repository: 'https://github.com/facebook/stylex',
    icon: 'stylex.png',
    keywords: ['stylex'],
    name: 'Stylex',
  },
  {
    homepage: 'https://windicss.org/',
    repository: 'https://github.com/windicss/windicss',
    icon: 'windicss.png',
    keywords: ['windicss', 'css'],
    name: 'Windi CSS',
  },
  {
    homepage: 'https://linaria.dev/',
    repository: 'https://github.com/callstack/linaria',
    icon: 'linaria.png',
    keywords: ['linaria', 'css'],
    name: 'Linaria',
  },
  {
    homepage: 'https://theme-ui.com/',
    repository: 'https://github.com/system-ui/theme-ui',
    icon: 'theme-ui.png',
    keywords: ['theme-ui', 'css'],
    name: 'Theme UI',
    darkInvert: true,
  },
  {
    homepage: 'https://fela.js.org/',
    repository: 'https://github.com/robinweser/fela',
    icon: 'fela.png',
    keywords: ['fela', 'css'],
    name: 'Fela',
  },
  {
    homepage: 'https://styled-system.com/',
    repository: 'https://github.com/styled-system/styled-system',
    icon: 'styled-system.png',
    keywords: ['styled-system', 'css'],
    name: 'StyledSystem',
    darkInvert: true,
  },
  {
    homepage: 'https://stitches.dev/',
    repository: 'https://github.com/stitchesjs/stitches',
    icon: 'stitches.png',
    keywords: ['stitches', 'css'],
    name: 'Stitches',
    darkInvert: true,
  },
]
