export default <AppItem[]>[
  {
    homepage: 'https://pinia.vuejs.org/',
    repository: 'https://github.com/posva/pinia',
    icon: 'pinia.png',
    keywords: ['pinia'],
    name: 'Pinia',
  },
  {
    homepage: 'https://redux.js.org/',
    repository: 'https://github.com/reduxjs/redux',
    icon: 'redux.png',
    keywords: ['redux'],
    name: 'Redux',
  },
  {
    homepage: 'https://reacttraining.com/react-router/',
    repository: 'https://github.com/ReactTraining/react-router',
    icon: 'react-router.png',
    keywords: ['reactrouter'],
    name: 'ReactRouter',
  },
  {
    homepage: 'https://graphql.org/',
    repository: 'https://github.com/graphql/graphiql',
    icon: 'graphql.png',
    keywords: ['graphql'],
    name: 'GraphQL',
  },
  {
    homepage: 'https://www.apollographql.com/',
    repository: 'https://github.com/apollographql',
    icon: 'apollographql.png',
    keywords: ['apollographql'],
    name: 'Apollo',
  },
  {
    homepage: 'https://lerna.js.org/',
    repository: 'https://github.com/lerna/lerna',
    icon: 'lerna.png',
    keywords: ['lerna'],
    name: 'Lerna',
    darkInvert: true,
  },
  {
    homepage: 'https://pre-commit.com/',
    repository: 'https://github.com/pre-commit/pre-commit',
    icon: 'pre-commit.png',
    keywords: ['pre-commit'],
    name: 'PreCommit',
  },
  {
    homepage: 'https://lodash.com/',
    repository: 'https://github.com/lodash/lodash/',
    icon: 'lodash.png',
    keywords: ['lodash'],
    name: 'Lodash',
  },
  {
    homepage: 'https://vueuse.org/',
    repository: 'https://github.com/vueuse/vueuse',
    icon: 'vueuse.png',
    keywords: ['vueuse'],
    name: 'VueUse',
  },
  {
    homepage: 'https://ahooks.js.org/',
    repository: 'https://github.com/alibaba/hooks',
    icon: 'ahooks.png',
    keywords: ['ahooks', 'react'],
    name: 'Ahooks',
  },
  {
    homepage: 'https://dojotoolkit.org/',
    repository: 'https://github.com/dojo/dojo',
    icon: 'dojo.png',
    keywords: ['dojo'],
    name: 'Dojo',
  },
  {
    homepage: 'https://immutable-js.github.io/immutable-js/',
    repository: 'https://github.com/immutable-js/immutable-js',
    icon: 'immutable.png',
    keywords: ['immutable'],
    name: 'Immutable',
  },
  {
    homepage: 'https://jquery.com/',
    repository: 'https://github.com/jquery/jquery',
    icon: 'jquery.png',
    keywords: ['jquery'],
    name: 'jQuery',
  },
  {
    homepage: 'https://zeptojs.com/',
    repository: 'https://github.com/madrobby/zepto/',
    icon: 'zepto.png',
    keywords: ['zepto'],
    name: 'Zepto',
  },
  {
    homepage: 'https://axios-http.com/',
    repository: 'https://github.com/axios/axios',
    icon: 'axios.png',
    keywords: ['axios'],
    name: 'Axios',
    darkInvert: true,
  },
  {
    homepage: 'http://mockjs.com/',
    repository: 'https://github.com/nuysoft/Mock',
    icon: 'mockjs.png',
    keywords: ['mockjs'],
    name: 'MockJS',
  },
  {
    homepage: 'https://fakerjs.dev/',
    repository: 'https://github.com/faker-js/faker',
    icon: 'faker.png',
    keywords: ['faker'],
    name: 'faker',
  },
  {
    homepage: 'https://momentjs.com/',
    repository: 'https://github.com/moment/moment',
    icon: 'moment.png',
    keywords: ['moment'],
    name: 'Moment',
  },
  {
    homepage: 'https://day.js.org/',
    repository: 'https://github.com/iamkun/dayjs',
    icon: 'dayjs.png',
    keywords: ['dayjs'],
    name: 'DayJS',
  },
  {
    homepage: 'https://date-fns.org/',
    repository: 'https://github.com/date-fns/date-fns',
    icon: 'date-fns.png',
    keywords: ['date-fns'],
    name: 'DateFNS',
  },
  {
    homepage: 'https://mochajs.org/',
    repository: 'https://github.com/mochajs/mocha',
    icon: 'mocha.png',
    keywords: ['mocha'],
    name: 'Mocha',
  },
  {
    homepage: 'https://testing-library.com/',
    repository: 'https://github.com/testing-library',
    icon: 'testing-library.png',
    keywords: ['testing-library'],
    name: 'TestingLibrary',
  },
  {
    homepage: 'https://www.cypress.io/',
    repository: 'https://github.com/cypress-io/cypress',
    icon: 'cypress.png',
    keywords: ['cypress'],
    name: 'Cypress',
  },
  {
    homepage: 'https://ava.li/',
    repository: 'https://github.com/avajs/ava',
    icon: 'ava.png',
    keywords: ['ava'],
    name: 'AVA',
  },
  {
    homepage: 'https://miragejs.com/',
    repository: 'https://github.com/miragejs',
    icon: 'mirage.png',
    keywords: ['mirage'],
    name: 'Mirage',
  },
  {
    homepage: 'https://highlightjs.org/',
    repository: 'https://github.com/highlightjs/highlight.js',
    icon: 'hljs.png',
    keywords: ['highlightjs', 'highlight.js', 'hljs'],
    name: 'HighlightJS',
  },
  {
    homepage: 'http://logic-flow.org/',
    repository: 'https://github.com/didi/LogicFlow',
    icon: 'logic-flow.png',
    keywords: ['logic-flow'],
    name: 'LogicFlow',
  },
  {
    homepage: 'https://threejs.org/',
    repository: 'https://github.com/mrdoob/three.js/',
    icon: 'three.js.png',
    keywords: ['threejs', 'three.js'],
    name: 'ThreeJS',
    darkInvert: true,
  },
  {
    homepage: 'https://pptr.dev/',
    repository: 'https://github.com/GoogleChrome/puppeteer',
    icon: 'puppeteer.png',
    keywords: ['pptr', 'puppeteer'],
    name: 'Puppeteer',
  },
  {
    homepage: 'https://yeoman.io/',
    repository: 'https://github.com/yeoman/yo',
    icon: 'yeoman.png',
    keywords: ['yo', 'yeoman'],
    name: 'Yeoman',
  },
  {
    homepage: 'https://socket.io/',
    repository: 'https://github.com/socketio/socket.io',
    icon: 'socket-io.png',
    keywords: ['socketio'],
    name: 'SocketIO',
  },
  {
    homepage: 'http://docs.sequelizejs.com/',
    repository: 'https://github.com/sequelize/sequelize',
    icon: 'sequelize.png',
    keywords: ['sequelize'],
    name: 'Sequelize',
  },
  {
    homepage: 'https://webassembly.org/',
    repository: 'https://github.com/WebAssembly',
    icon: 'webassembly.png',
    keywords: ['WebAssembly'],
    name: 'WebAssembly',
  },
];
