export default <AppItem[]>[
  {
    homepage: 'https://nodejs.dev/',
    repository: 'https://github.com/nodejs/node/',
    icon: 'nodejs.png',
    keywords: ['nodejs'],
    name: 'NodeJS',
  },
  {
    homepage: 'https://deno.land/',
    repository: 'https://github.com/denoland',
    icon: 'deno.png',
    keywords: ['deno'],
    name: 'Deno',
  },
  {
    homepage: 'https://bun.sh/',
    repository: 'https://github.com/oven-sh/bun',
    icon: 'bun.png',
    keywords: ['bun'],
    name: 'Bun',
  },
  {
    homepage: 'https://nestjs.com/',
    repository: 'https://github.com/nestjs/nest/',
    icon: 'nest.png',
    keywords: ['nest'],
    name: 'Nest',
  },
  {
    homepage: 'http://expressjs.com/',
    repository: 'https://github.com/expressjs/express',
    icon: 'express.png',
    keywords: ['express'],
    name: 'Express',
    darkInvert: true,
  },
  {
    homepage: 'https://koajs.com/',
    repository: 'https://github.com/koajs/koa',
    icon: 'koa.png',
    keywords: ['koa'],
    name: 'Koa',
    darkInvert: true,
  },
  {
    homepage: 'https://www.fastify.io/',
    repository: 'https://github.com/fastify/fastify',
    icon: 'fastify.png',
    keywords: ['fastify'],
    name: 'Fastify',
    darkInvert: true,
  },
  {
    homepage: 'https://sailsjs.com/',
    repository: 'https://github.com/balderdashy/sails',
    icon: 'sails.png',
    keywords: ['sails'],
    name: 'Sails',
  },
  {
    homepage: 'https://eggjs.org/',
    repository: 'https://github.com/eggjs/egg/',
    icon: 'egg.png',
    keywords: ['egg'],
    name: 'Egg',
  },
  {
    homepage: 'https://adonisjs.com/',
    repository: 'https://github.com/adonisjs/core',
    icon: 'adonis.png',
    keywords: ['adonis'],
    name: 'Adonis',
  },
  {
    homepage: 'https://hono.dev/',
    repository: 'https://github.com/honojs/hono',
    icon: 'hono.png',
    keywords: ['hono'],
    name: 'Hono',
  },
  {
    homepage: 'https://hapijs.com/',
    repository: 'https://github.com/hapijs/hapi',
    icon: 'hapi.png',
    keywords: ['hapi'],
    name: 'Hapi',
  },
  {
    homepage: 'https://elysiajs.com/',
    repository: 'https://github.com/elysiajs/elysia',
    icon: 'elysiajs.png',
    keywords: ['elysia'],
    name: 'Elysia',
  },
  {
    homepage: 'https://feathersjs.com/',
    repository: 'https://github.com/feathersjs/feathers',
    icon: 'feathers.png',
    keywords: ['feathers'],
    name: 'Feathers',
    darkInvert: true,
  },
  {
    homepage: 'http://restify.com/',
    repository: 'https://github.com/restify/node-restify',
    icon: 'restify.png',
    keywords: ['restify'],
    name: 'Restify',
  },
  {
    homepage: 'https://midwayjs.org/',
    repository: 'https://github.com/midwayjs/midway',
    icon: 'midwayjs.png',
    keywords: ['midwayjs'],
    name: 'Midway',
  },
  {
    homepage: 'https://moleculer.services/',
    repository: 'https://github.com/moleculerjs/moleculer',
    icon: 'moleculer.png',
    keywords: ['moleculer'],
    name: 'Moleculer',
  },
  {
    homepage: 'https://thinkjs.org/',
    repository: 'https://github.com/thinkjs/thinkjs',
    icon: 'thinkjs.png',
    keywords: ['thinkjs'],
    name: 'Thinkjs',
  },
  {
    homepage: 'https://loopback.io/',
    repository: 'https://github.com/loopbackio/loopback-next',
    icon: 'loopback.png',
    keywords: ['loopback'],
    name: 'LoopBack',
  },
  {
    homepage: 'https://senecajs.org/',
    repository: 'https://github.com/senecajs/seneca',
    icon: 'seneca.png',
    keywords: ['seneca'],
    name: 'Seneca',
    darkInvert: true,
  },
  {
    homepage: 'https://tinyhttp.v1rtl.site/',
    repository: 'https://github.com/tinyhttp/tinyhttp',
    icon: 'tinyhttp.png',
    keywords: ['tinyhttp'],
    name: 'Tinyhttp',
  },
  {
    homepage: 'https://www.actionherojs.com/',
    repository: 'https://github.com/actionhero/actionhero',
    icon: 'actionhero.png',
    keywords: ['actionhero'],
    name: 'Actionhero',
  },
  {
    homepage: 'https://docs.marblejs.com/',
    repository: 'https://github.com/marblejs/marble',
    icon: 'marble.png',
    keywords: ['marble'],
    name: 'Marble',
  },
  {
    homepage: 'https://hemerajs.github.io/hemera/',
    repository: 'https://github.com/hemerajs/hemera',
    icon: 'hemera.png',
    keywords: ['hemera'],
    name: 'Hemera',
    darkInvert: true,
  },
  {
    homepage: 'https://v8.dev/',
    repository: 'https://github.com/v8/v8',
    icon: 'v8.png',
    keywords: ['v8'],
    name: 'V8',
  },
  {
    homepage: 'https://libuv.org/',
    repository: 'https://github.com/libuv/libuv',
    icon: 'libuv.png',
    keywords: ['libuv'],
    name: 'libuv',
  },
]
