export default <AppItem[]>[
  {
    homepage: 'https://deno.land/',
    repository: 'https://github.com/denoland',
    icon: 'deno.png',
    keywords: ['deno'],
    name: 'Deno',
  },
  {
    homepage: 'https://bun.sh/',
    repository: 'https://github.com/oven-sh/bun',
    icon: 'bun.png',
    keywords: ['bun'],
    name: 'Bun',
  },
  {
    homepage: 'https://golang.org/',
    repository: 'https://github.com/golang/go/',
    icon: 'golang.png',
    keywords: ['golang'],
    name: 'Golang',
  },
  {
    homepage: 'https://www.rust-lang.org/',
    repository: 'https://github.com/rust-lang/rust',
    icon: 'rust.png',
    keywords: ['rust'],
    name: 'Rust',
    darkInvert: true,
  },
  {
    homepage: 'https://ziglang.org/',
    repository: 'https://github.com/ziglang/zig',
    icon: 'zig.png',
    keywords: ['zig'],
    name: 'Zig',
  },
  {
    homepage: 'https://www.ruby-lang.org/',
    repository: 'https://github.com/ruby/ruby/',
    icon: 'ruby.png',
    keywords: ['ruby'],
    name: 'Ruby',
  },
  {
    homepage: 'https://www.dartlang.org/',
    repository: 'https://github.com/dart-lang/',
    icon: 'dart.png',
    keywords: ['dart'],
    name: 'Dart',
  },
  {
    homepage: 'https://www.python.org/',
    repository: 'https://github.com/python',
    icon: 'python.png',
    keywords: ['python'],
    name: 'Python',
  },
  {
    homepage: 'https://www.php.net/',
    repository: 'https://github.com/php',
    icon: 'php.png',
    keywords: ['php'],
    name: 'PHP',
  },
  {
    homepage: 'https://www.docker.com/',
    repository: 'https://github.com/docker',
    icon: 'docker.png',
    keywords: ['docker'],
    name: 'Docker',
  },
  {
    homepage: 'http://nginx.org/',
    repository: 'https://github.com/nginx',
    icon: 'nginx.png',
    keywords: ['nginx'],
    name: 'Nginx',
  },
  {
    homepage: 'https://redis.io/',
    repository: 'https://github.com/redis',
    icon: 'redis.png',
    keywords: ['redis'],
    name: 'Redis',
  },
  {
    homepage: 'https://spring.io/',
    repository: 'https://github.com/spring-projects',
    icon: 'spring.png',
    keywords: ['spring'],
    name: 'Spring',
  },
  {
    homepage: 'https://hadoop.apache.org/',
    repository: 'https://github.com/apache/hadoop',
    icon: 'hadoop.png',
    keywords: ['hadoop'],
    name: 'Hadoop',
  },
  {
    homepage: 'https://www.mysql.com/',
    repository: 'https://github.com/mysql',
    icon: 'mysql.png',
    keywords: ['mysql'],
    name: 'MySQL',
  },
  {
    homepage: 'https://www.mongodb.com/',
    repository: 'https://github.com/mongodb',
    icon: 'mongodb.png',
    keywords: ['mongodb'],
    name: 'MongoDB',
  },
  {
    homepage: 'https://v8.dev/',
    repository: 'https://github.com/v8/v8',
    icon: 'v8.png',
    keywords: ['v8'],
    name: 'V8',
  },
]
