export default <AppItem[]>[
  {
    homepage: 'https://www.python.org/',
    repository: 'https://github.com/python',
    icon: 'python.png',
    keywords: ['python lang'],
    name: 'Python',
  },
  {
    homepage: 'https://www.java.com/',
    icon: 'java.png',
    keywords: ['java'],
    name: 'Java',
  },
  {
    homepage: 'https://wikipedia.org/wiki/C_(programming_language)',
    icon: 'c.png',
    keywords: ['c lang'],
    name: 'C',
  },
  {
    homepage: 'https://cppreference.com/',
    icon: 'c++.png',
    keywords: ['c++ lang', 'cplusplus lang'],
    name: 'C++',
  },
  {
    homepage: 'https://dotnet.microsoft.com/languages/csharp',
    repository: 'https://github.com/dotnet/csharplang',
    icon: 'csharp.png',
    keywords: ['csharp lang', 'c# lang'],
    name: 'C#',
  },
  {
    homepage: 'https://golang.org/',
    repository: 'https://github.com/golang/go/',
    icon: 'go.png',
    keywords: ['go lang'],
    name: 'Go',
  },
  {
    homepage: 'https://www.rust-lang.org/',
    repository: 'https://github.com/rust-lang/rust',
    icon: 'rust.png',
    keywords: ['rust lang'],
    name: 'Rust',
    darkInvert: true,
  },
  {
    homepage: 'https://ziglang.org/',
    repository: 'https://github.com/ziglang/zig',
    icon: 'zig.png',
    keywords: ['zig lang'],
    name: 'Zig',
  },
  {
    homepage: 'https://www.php.net/',
    repository: 'https://github.com/php',
    icon: 'php.png',
    keywords: ['php lang'],
    name: 'PHP',
  },
  {
    homepage: 'https://www.swift.org/',
    repository: 'https://github.com/swiftlang/swift',
    icon: 'swift.png',
    keywords: ['swift lang'],
    name: 'Swift',
  },
  {
    homepage: 'https://kotlinlang.org/',
    repository: 'https://github.com/JetBrains/kotlin',
    icon: 'kotlin.png',
    keywords: ['kotlin lang'],
    name: 'Kotlin',
    lessRadius: true,
  },
  {
    homepage: 'https://www.ruby-lang.org/',
    repository: 'https://github.com/ruby/ruby/',
    icon: 'ruby.png',
    keywords: ['ruby lang'],
    name: 'Ruby',
  },
  {
    homepage: 'https://www.dartlang.org/',
    repository: 'https://github.com/dart-lang/',
    icon: 'dart.png',
    keywords: ['dart lang'],
    name: 'Dart',
  },
  {
    homepage: 'https://www.r-project.org/',
    icon: 'r.png',
    keywords: ['r lang'],
    name: 'R',
  },
  {
    homepage: 'https://www.scala-lang.org/',
    repository: 'https://github.com/scala',
    icon: 'scala.png',
    keywords: ['scala lang'],
    name: 'Scala',
  },
  {
    homepage: 'https://lua.org/',
    icon: 'lua.png',
    keywords: ['lua lang'],
    name: 'Lua',
  },
  {
    homepage: 'https://www.haskell.org/',
    repository: 'https://github.com/haskell-infra',
    icon: 'haskell.png',
    keywords: ['haskell lang'],
    name: 'Haskell',
  },
  {
    homepage: 'https://www.docker.com/',
    repository: 'https://github.com/docker',
    icon: 'docker.png',
    keywords: ['docker'],
    name: 'Docker',
  },
  {
    homepage: 'http://nginx.org/',
    repository: 'https://github.com/nginx',
    icon: 'nginx.png',
    keywords: ['nginx'],
    name: 'Nginx',
  },
  {
    homepage: 'https://redis.io/',
    repository: 'https://github.com/redis',
    icon: 'redis.png',
    keywords: ['redis'],
    name: 'Redis',
  },
  {
    homepage: 'https://www.djangoproject.com/',
    repository: 'https://github.com/django',
    icon: 'django.png',
    keywords: ['django'],
    name: 'Django',
  },
  {
    homepage: 'https://spring.io/',
    repository: 'https://github.com/spring-projects',
    icon: 'spring.png',
    keywords: ['spring'],
    name: 'Spring',
  },
  {
    homepage: 'https://hadoop.apache.org/',
    repository: 'https://github.com/apache/hadoop',
    icon: 'hadoop.png',
    keywords: ['hadoop'],
    name: 'Hadoop',
  },
  {
    homepage: 'https://www.mysql.com/',
    repository: 'https://github.com/mysql',
    icon: 'mysql.png',
    keywords: ['mysql'],
    name: 'MySQL',
  },
  {
    homepage: 'https://www.mongodb.com/',
    repository: 'https://github.com/mongodb',
    icon: 'mongodb.png',
    keywords: ['mongodb'],
    name: 'MongoDB',
  },
]
