export default <AppItem[]>[
  {
    homepage: 'https://www.baidu.com/',
    repository: 'https://github.com/baidu',
    icon: 'baidu.png',
    keywords: ['百度', 'baidu'],
    name: '百度',
  },
  {
    homepage: 'https://www.google.com/',
    repository: 'https://github.com/google',
    icon: 'google.png',
    keywords: ['谷歌', 'google'],
    name: 'Google',
  },
  {
    homepage: 'https://www.microsoft.com/',
    repository: 'https://github.com/microsoft',
    icon: 'microsoft.png',
    keywords: ['微软', 'Microsoft'],
    name: 'Microsoft',
  },
  {
    homepage: 'https://openai.com/',
    repository: 'https://github.com/openai',
    icon: 'openai.png',
    keywords: ['openai'],
    name: 'OpenAI',
    darkInvert: true,
  },
  {
    homepage: 'https://claude.ai/',
    icon: 'claude.png',
    keywords: ['claude', 'ai'],
    name: 'Claude',
    lessRadius: true,
  },
  {
    homepage: 'https://gemini.google.com/',
    icon: 'bard.png',
    keywords: ['bard', 'gemini', 'ai'],
    name: 'Gemini',
  },
  {
    homepage: 'https://www.perplexity.ai/',
    icon: 'perplexity.png',
    keywords: ['perplexity', 'ai'],
    name: 'Perplexity',
  },
  {
    homepage: 'https://runwayml.com/',
    icon: 'runway.png',
    keywords: ['runway', 'ai'],
    name: 'Runway',
    darkInvert: true,
  },
  {
    homepage: 'https://kimi.moonshot.cn/',
    icon: 'kimi.png',
    keywords: ['kimi', 'ai'],
    name: 'Kimi',
  },
  {
    homepage: 'https://www.coze.com/',
    icon: 'coze.png',
    keywords: ['coze', 'ai'],
    name: 'Coze',
  },
  {
    homepage: 'https://yiyan.baidu.com/',
    icon: 'wenxinyiyan.png',
    keywords: ['wenxinyiyan', '文心一言', 'ai'],
    name: '文心一言',
  },
  {
    homepage: 'https://tongyi.aliyun.com/',
    icon: 'tongyi.png',
    keywords: ['tongyi', '通义', 'ai'],
    name: '通义',
  },
  {
    homepage: 'https://x.com/',
    repository: 'https://github.com/twitter',
    icon: 'x.png',
    keywords: ['x', 'twitter'],
    name: 'X',
  },
  {
    homepage: 'https://about.facebook.com/meta',
    repository: 'https://github.com/facebook',
    icon: 'meta.png',
    keywords: ['facebook', 'meta'],
    name: 'Meta',
  },
  {
    homepage: 'https://www.youtube.com/',
    repository: 'https://github.com/youtube',
    icon: 'youtube.png',
    keywords: ['youtube'],
    name: 'YouTube',
  },
  {
    homepage: 'https://github.com/',
    repository: 'https://github.com/github',
    icon: 'github.png',
    keywords: ['github'],
    name: 'GitHub',
  },
  {
    homepage: 'https://gitlab.com/',
    repository: 'https://github.com/gitlabhq',
    icon: 'gitlab.png',
    keywords: ['gitlab'],
    name: 'GitLab',
  },
  {
    homepage: 'https://git-scm.com/',
    repository: 'https://github.com/git/git',
    icon: 'git.png',
    keywords: ['git'],
    name: 'Git',
  },
  {
    homepage: 'https://www.npmjs.com/',
    repository: 'https://github.com/npm',
    icon: 'npm.png',
    keywords: ['npm'],
    name: 'NPM',
  },
  {
    homepage: 'https://yarnpkg.com/',
    repository: 'https://github.com/yarnpkg/berry',
    icon: 'yarn.png',
    keywords: ['yarn'],
    name: 'Yarn',
  },
  {
    homepage: 'https://pnpm.io/',
    repository: 'https://github.com/pnpm/pnpm',
    icon: 'pnpm.png',
    keywords: ['pnpm'],
    name: 'PNPM',
  },
  {
    homepage: 'https://bower.io/',
    repository: 'https://github.com/bower/bower',
    icon: 'bower.png',
    keywords: ['bower'],
    name: 'Bower',
  },
  {
    homepage: 'https://www.jsdelivr.com/',
    repository: 'https://github.com/jsdelivr/jsdelivr',
    icon: 'jsdelivr.png',
    keywords: ['jsdelivr', 'cdn'],
    name: 'JSDelivr',
  },
  {
    homepage: 'https://cdnjs.com/',
    repository: 'https://github.com/cdnjs/cdnjs',
    icon: 'cdnjs.png',
    keywords: ['cdnjs', 'cdn'],
    name: 'CDNJS',
  },
  {
    homepage: 'https://unpkg.com/',
    repository: 'https://github.com/mjackson/unpkg',
    icon: 'unpkg.png',
    keywords: ['unpkg', 'cdn'],
    name: 'UNPKG',
    darkInvert: true,
  },
  {
    homepage: 'https://esm.sh/',
    repository: 'https://github.com/ije/esm.sh',
    icon: 'esm-cdn.png',
    keywords: ['esm', 'cdn'],
    name: 'ESM',
    darkInvert: true,
  },
  {
    homepage: 'https://www.skypack.dev/',
    repository: 'https://github.com/skypackjs',
    icon: 'skypack.png',
    keywords: ['skypack', 'cdn'],
    name: 'Skypack',
  },
  {
    homepage: 'https://www.bootcdn.cn/',
    icon: 'bootcdn.png',
    keywords: ['bootcdn', 'cdn'],
    name: 'BootCDN',
  },
  {
    homepage: 'https://developer.mozilla.org/',
    repository: 'https://github.com/mdn',
    icon: 'mdn.png',
    keywords: ['mdn'],
    name: 'MDN',
  },
  {
    homepage: 'https://web.dev/',
    icon: 'webdev.png',
    keywords: ['web dev'],
    name: 'web.dev',
  },
  {
    homepage: 'https://javascript.info/',
    repository: 'https://github.com/javascript-tutorial',
    icon: 'javascript-tutorial.png',
    keywords: ['javascript-tutorial', 'js'],
    name: 'JSTutorial',
  },
  {
    homepage: 'https://stackoverflow.com/',
    icon: 'stackoverflow.png',
    keywords: ['stack overflow'],
    name: 'StackOverflow',
  },
  {
    homepage: 'https://caniuse.com/',
    repository: 'https://github.com/fyrd/caniuse',
    icon: 'caniuse.png',
    keywords: ['caniuse'],
    name: 'Can I use',
  },
  {
    homepage: 'https://travis-ci.org/',
    repository: 'https://github.com/travis-ci',
    icon: 'travis.png',
    keywords: ['travis', 'ci'],
    name: 'Travis',
  },
  {
    homepage: 'https://www.jenkins.io/',
    repository: 'https://github.com/jenkinsci',
    icon: 'jenkins.png',
    keywords: ['jenkins', 'ci'],
    name: 'Jenkins',
  },
  {
    homepage: 'https://code.visualstudio.com/',
    repository: 'https://github.com/microsoft/vscode',
    icon: 'vscode.png',
    keywords: ['vscode'],
    name: 'VSCode',
  },
  {
    homepage: 'https://www.jetbrains.com/webstorm/',
    icon: 'webstorm.png',
    keywords: ['webstorm'],
    name: 'WebStorm',
  },
  {
    homepage: 'http://www.sublimetext.com/',
    icon: 'sublimetext.png',
    keywords: ['sublimetext'],
    name: 'SublimeText',
  },
  {
    homepage: 'https://zeabur.com/',
    repository: 'https://github.com/zeabur/zeabur',
    icon: 'zeabur.png',
    keywords: ['zeabur'],
    name: 'Zeabur',
    lessRadius: true,
  },
  {
    homepage: 'https://www.cloudflare.com/',
    repository: 'https://github.com/cloudflare',
    icon: 'cloudflare.png',
    keywords: ['cloudflare'],
    name: 'Cloudflare',
  },
  {
    homepage: 'https://app.netlify.com/',
    repository: 'https://github.com/netlify',
    icon: 'netlify.png',
    keywords: ['netlify'],
    name: 'Netlify',
  },
  {
    homepage: 'https://vercel.com/login',
    repository: 'https://github.com/vercel/vercel',
    icon: 'vercel.png',
    keywords: ['vercel'],
    name: 'Vercel',
  },
  {
    homepage: 'https://firebase.google.cn/',
    repository: 'https://github.com/firebase/',
    icon: 'firebase.png',
    keywords: ['firebase'],
    name: 'Firebase',
  },
  {
    homepage: 'https://stackblitz.com/',
    repository: 'https://github.com/stackblitz/core',
    icon: 'stackblitz.png',
    keywords: ['stackblitz'],
    name: 'StackBlitz',
  },
  {
    homepage: 'https://codesandbox.io/',
    repository: 'https://github.com/codesandbox/codesandbox-client',
    icon: 'codesandbox.png',
    keywords: ['codesandbox'],
    name: 'CodeSandbox',
    darkInvert: true,
  },
  {
    homepage: 'https://github.com/jsfiddle',
    repository: 'https://jsfiddle.net/',
    icon: 'js-fiddle.png',
    keywords: ['js-fiddle'],
    name: 'JSFiddle',
  },
  {
    homepage: 'https://codepen.io/',
    icon: 'codepen.png',
    keywords: ['codepen'],
    name: 'CodePen',
    darkInvert: true,
  },
  {
    homepage: 'https://tinypng.com/',
    repository: 'https://github.com/tinify',
    icon: 'tinypng.png',
    keywords: ['tinypng'],
    name: 'TinyPNG',
  },
  {
    homepage: 'https://dev.to/',
    icon: 'devto.png',
    keywords: ['dev'],
    name: 'DEV',
    darkInvert: true,
  },
  {
    homepage: 'https://medium.com/',
    repository: 'https://github.com/Medium',
    icon: 'medium.png',
    keywords: ['medium'],
    name: 'Medium',
    darkInvert: true,
  },
  {
    homepage: 'https://css-tricks.com/',
    icon: 'css-tricks.png',
    keywords: ['css-tricks'],
    name: 'CSS Tricks',
  },
  {
    homepage: 'https://www.smashingmagazine.com/',
    icon: 'smashing-magazine.png',
    keywords: ['smashing-magazine'],
    name: 'SmashingMagazine',
  },
  {
    homepage: 'https://www.producthunt.com/',
    repository: 'https://github.com/producthunt',
    icon: 'producthunt.png',
    keywords: ['producthunt'],
    name: 'Product Hunt',
  },
  {
    homepage: 'https://www.yuque.com/',
    repository: 'https://github.com/yuque',
    icon: 'yuque.png',
    keywords: ['语雀', 'yuque'],
    name: '语雀',
  },
  {
    homepage: 'https://www.feishu.cn/',
    icon: 'feishu.png',
    keywords: ['飞书', 'feishu'],
    name: '飞书',
  },
  {
    homepage: 'https://www.xiaohongshu.com/',
    icon: 'xhs.png',
    keywords: ['小红书', 'xiaohongshu', 'xhs'],
    name: '小红书',
  },
  {
    homepage: 'https://juejin.im/',
    repository: 'https://github.com/xitu',
    icon: 'juejin.png',
    keywords: ['掘金', 'juejin'],
    name: '掘金',
  },
  {
    homepage: 'https://segmentfault.com/',
    icon: 'sf.png',
    keywords: ['segmentfault', 'sf', '思否', 'sifou'],
    name: '思否',
  },
  {
    homepage: 'https://www.zhihu.com/',
    repository: 'https://github.com/zhihu',
    icon: 'zhihu.png',
    keywords: ['知乎', 'zhihu'],
    name: '知乎',
  },
  {
    homepage: 'https://kb.cnblogs.com/',
    icon: 'cnblogs.png',
    keywords: ['博客园', 'cnblogs', 'bokeyuan'],
    name: '博客园',
    darkInvert: true,
  },
  {
    homepage: 'https://www.jianshu.com/',
    icon: 'jianshu.png',
    keywords: ['简书', 'jianshu'],
    name: '简书',
  },
]
