export default<AppItem[]> [{
  homepage: 'https://www.baidu.com/',
  repository: 'https://github.com/baidu',
  icon: 'baidu.png',
  keywords: ['百度', 'baidu'],
  name: '百度',
}, {
  homepage: 'https://www.google.com/',
  repository: 'https://github.com/google',
  icon: 'google.png',
  keywords: ['谷歌', 'google'],
  name: 'Google',
}, {
  homepage: 'https://www.microsoft.com/',
  repository: 'https://github.com/microsoft',
  icon: 'microsoft.png',
  keywords: ['微软', 'Microsoft'],
  name: 'Microsoft',
}, {
  homepage: 'https://about.facebook.com/meta',
  repository: 'https://github.com/facebook',
  icon: 'meta.png',
  keywords: ['facebook', 'meta'],
  name: 'Meta',
}, {
  homepage: 'https://github.com/',
  repository: 'https://github.com/github',
  icon: 'github.png',
  keywords: ['github'],
  name: 'GitHub',
}, {
  homepage: 'https://gitlab.com/',
  icon: 'gitlab.png',
  keywords: ['gitlab'],
  name: 'GitLab',
}, {
  homepage: 'https://git-scm.com/',
  repository: 'https://github.com/git/git',
  icon: 'git.png',
  keywords: ['git'],
  name: 'Git',
}, {
  homepage: 'https://www.npmjs.com/',
  repository: 'https://github.com/npm',
  icon: 'npm.png',
  keywords: ['npm'],
  name: 'NPM',
}, {
  homepage: 'https://yarnpkg.com/',
  repository: 'https://github.com/yarnpkg/yarn',
  icon: 'yarn.png',
  keywords: ['yarn'],
  name: 'Yarn',
}, {
  homepage: 'https://pnpm.io/',
  repository: 'https://github.com/pnpm/pnpm',
  icon: 'pnpm.png',
  keywords: ['pnpm'],
  name: 'PNPM',
}, {
  homepage: 'https://bower.io/',
  repository: 'https://github.com/bower/bower',
  icon: 'bower.png',
  keywords: ['bower'],
  name: 'Bower',
}, {
  homepage: 'https://www.jsdelivr.com/',
  repository: 'https://github.com/jsdelivr/jsdelivr',
  icon: 'jsdelivr.png',
  keywords: ['jsdelivr', 'cdn'],
  name: 'JSDelivr',
}, {
  homepage: 'https://cdnjs.com/',
  repository: 'https://github.com/cdnjs/cdnjs',
  icon: 'cdnjs.png',
  keywords: ['cdnjs', 'cdn'],
  name: 'CDNJS',
}, {
  homepage: 'https://unpkg.com/',
  repository: 'https://github.com/mjackson/unpkg',
  icon: 'unpkg.png',
  keywords: ['unpkg', 'cdn'],
  name: 'UNPKG',
  darkInvert: true,
}, {
  homepage: 'https://esm.sh/',
  repository: 'https://github.com/ije/esm.sh',
  icon: 'esm-cdn.png',
  keywords: ['esm', 'cdn'],
  name: 'ESM',
  darkInvert: true,
}, {
  homepage: 'https://www.bootcdn.cn/',
  repository: 'https://github.com/bootcdn',
  icon: 'bootcdn.png',
  keywords: ['bootcdn', 'cdn'],
  name: 'BootCDN',
}, {
  homepage: 'https://developer.mozilla.org/',
  repository: 'https://github.com/mdn',
  icon: 'mdn.png',
  keywords: ['mdn'],
  name: 'MDN',
}, {
  homepage: 'https://javascript.info/',
  repository: 'https://github.com/javascript-tutorial',
  icon: 'javascript-tutorial.png',
  keywords: ['javascript-tutorial', 'js'],
  name: 'JSTutorial',
}, {
  homepage: 'https://stackoverflow.com/',
  icon: 'stackoverflow.png',
  keywords: ['stack overflow'],
  name: 'StackOverflow',
}, {
  homepage: 'https://caniuse.com/',
  repository: 'https://github.com/fyrd/caniuse',
  icon: 'caniuse.png',
  keywords: ['caniuse'],
  name: 'Can I use',
}, {
  homepage: 'https://travis-ci.org/',
  repository: 'https://github.com/travis-ci',
  icon: 'travis.png',
  keywords: ['travis', 'ci'],
  name: 'Travis',
}, {
  homepage: 'https://www.jenkins.io/',
  repository: 'https://github.com/jenkinsci',
  icon: 'jenkins.png',
  keywords: ['jenkins', 'ci'],
  name: 'Jenkins',
}, {
  homepage: 'https://code.visualstudio.com/',
  repository: 'https://github.com/microsoft/vscode',
  icon: 'vscode.png',
  keywords: ['vscode'],
  name: 'VSCode',
}, {
  homepage: 'https://www.jetbrains.com/webstorm/',
  icon: 'webstorm.png',
  keywords: ['webstorm'],
  name: 'WebStorm',
}, {
  homepage: 'http://www.sublimetext.com/',
  icon: 'sublimetext.png',
  keywords: ['sublimetext'],
  name: 'SublimeText',
}, {
  homepage: 'https://stackblitz.com/',
  repository: 'https://github.com/stackblitz/core',
  icon: 'stackblitz.png',
  keywords: ['stackblitz'],
  name: 'StackBlitz',
}, {
  homepage: 'https://codesandbox.io/',
  repository: 'https://github.com/codesandbox/codesandbox-client',
  icon: 'codesandbox.png',
  keywords: ['codesandbox'],
  name: 'CodeSandbox',
}, {
  homepage: 'https://github.com/jsfiddle',
  repository: 'https://jsfiddle.net/',
  icon: 'js-fiddle.png',
  keywords: ['js-fiddle'],
  name: 'JSFiddle',
}, {
  homepage: 'https://codepen.io/',
  icon: 'codepen.png',
  keywords: ['codepen'],
  name: 'CodePen',
  darkInvert: true,
}, {
  homepage: 'https://tinypng.com/',
  repository: 'https://github.com/tinify',
  icon: 'tinypng.png',
  keywords: ['tinypng'],
  name: 'TinyPNG',
}, {
  homepage: 'https://dev.to/',
  icon: 'devto.png',
  keywords: ['dev'],
  name: 'DEV',
  darkInvert: true,
}, {
  homepage: 'https://css-tricks.com/',
  icon: 'css-tricks.png',
  keywords: ['css-tricks'],
  name: 'CSS Tricks',
}, {
  homepage: 'https://www.smashingmagazine.com/',
  icon: 'smashing-magazine.png',
  keywords: ['smashing-magazine'],
  name: 'SmashingMagazine',
}, {
  homepage: 'https://juejin.im/',
  repository: 'https://github.com/xitu',
  icon: 'juejin.png',
  keywords: ['掘金', 'juejin'],
  name: '掘金',
}, {
  homepage: 'https://segmentfault.com/',
  icon: 'sf.png',
  keywords: ['segmentfault', 'sf', '思否', 'sifou'],
  name: '思否',
}, {
  homepage: 'https://www.zhihu.com/',
  icon: 'zhihu.png',
  keywords: ['知乎', 'zhihu'],
  name: '知乎',
}, {
  homepage: 'https://kb.cnblogs.com/',
  icon: 'cnblogs.png',
  keywords: ['博客园', 'cnblogs', 'bokeyuan'],
  name: '博客园',
  darkInvert: true,
}, {
  homepage: 'https://www.jianshu.com/',
  icon: 'jianshu.png',
  keywords: ['简书', 'jianshu'],
  name: '简书',
}]
