export default <AppItem[]>[
  {
    homepage: 'https://webpack.js.org/',
    repository: 'https://github.com/webpack/webpack',
    icon: 'webpack.png',
    keywords: ['webpack'],
    name: 'Webpack',
  },
  {
    homepage: 'https://esbuild.github.io/',
    repository: 'https://github.com/evanw/esbuild',
    icon: 'esbuild.png',
    keywords: ['esbuild'],
    name: 'Esbuild',
  },
  {
    homepage: 'https://swc.rs/',
    repository: 'https://github.com/swc-project/swc',
    icon: 'swc.png',
    keywords: ['swc'],
    name: 'SWC',
  },
  {
    homepage: 'https://rollupjs.org/',
    repository: 'https://github.com/rollup/rollup',
    icon: 'rollup.png',
    keywords: ['rollup'],
    name: 'Rollup',
  },
  {
    homepage: 'https://parceljs.org/',
    repository: 'https://github.com/parcel-bundler/parcel',
    icon: 'parcel.png',
    keywords: ['parcel'],
    name: 'Parcel',
  },
  {
    homepage: 'https://www.pika.dev/',
    repository: 'https://github.com/pikapkg/web',
    icon: 'pika.png',
    keywords: ['pika'],
    name: 'Pika',
  },
  {
    homepage: 'https://astro.build/',
    repository: 'https://github.com/withastro/astro',
    icon: 'astro.png',
    keywords: ['astro'],
    name: 'Astro',
  },
  {
    homepage: 'https://wmr.dev/',
    repository: 'https://github.com/preactjs/wmr',
    icon: 'wmr.png',
    keywords: ['wmr'],
    name: 'WMR',
  },
  {
    homepage: 'https://prepack.io/',
    repository: 'https://github.com/facebook/prepack',
    icon: 'prepack.png',
    keywords: ['prepack'],
    name: 'Prepack',
  },
  {
    homepage: 'https://gulpjs.com/',
    repository: 'https://github.com/gulpjs/gulp',
    icon: 'gulp.png',
    keywords: ['gulp'],
    name: 'Gulp',
  },
  {
    homepage: 'https://gruntjs.com/',
    repository: 'https://github.com/gruntjs/grunt',
    icon: 'grunt.png',
    keywords: ['grunt'],
    name: 'Grunt',
  },
  {
    homepage: 'http://browserify.org/',
    repository: 'https://github.com/browserify/browserify',
    icon: 'browserify.png',
    keywords: ['browserify'],
    name: 'Browserify',
  },
  {
    homepage: 'https://vitejs.dev/',
    repository: 'https://github.com/vitejs/vite',
    icon: 'vite.png',
    keywords: ['vite'],
    name: 'Vite',
  },
  {
    homepage: 'https://create-react-app.dev/',
    repository: 'https://github.com/facebook/create-react-app',
    icon: 'cra.png',
    keywords: ['cra', 'create-react-app'],
    name: 'CreateReactApp',
  },
  {
    homepage: 'https://github.com/google/zx',
    repository: 'https://github.com/google/zx',
    icon: 'zx.png',
    keywords: ['zx'],
    name: 'ZX',
  },
  {
    homepage: 'http://babeljs.io/',
    repository: 'https://github.com/babel/babel',
    icon: 'babel.png',
    keywords: ['babel'],
    name: 'Babel',
  },
  {
    homepage: [
      {
        href: 'https://eslint.org/',
        title: '英文官网',
      },
      {
        href: 'https://eslint.bootcss.com/',
        title: '中文官网',
      },
    ],
    repository: 'https://github.com/eslint/eslint',
    icon: 'eslint.png',
    keywords: ['eslint'],
    name: 'ESlint',
  },
  {
    homepage: 'https://jshint.com/',
    repository: 'https://github.com/jshint/jshint',
    icon: 'jshint.png',
    keywords: ['jshint'],
    name: 'JSHint',
  },
  {
    homepage: 'https://flow.org/',
    repository: 'https://github.com/facebook/flow',
    icon: 'flow.png',
    keywords: ['flow'],
    name: 'Flow',
  },
  {
    homepage: 'https://prettier.io/',
    repository: 'https://github.com/prettier/prettier',
    icon: 'prettier.png',
    keywords: ['prettier'],
    name: 'Prettier',
  },
  {
    homepage: 'https://www.typescriptlang.org/',
    repository: 'https://github.com/Microsoft/TypeScript',
    icon: 'typescript.png',
    keywords: ['typescript', 'ts'],
    name: 'TypeScript',
  },
  {
    homepage: 'https://www.assemblyscript.org/',
    repository: 'https://github.com/AssemblyScript/assemblyscript',
    icon: 'assemblyscript.png',
    keywords: ['assemblyscript', 'as'],
    name: 'AssemblyScript',
  },
  {
    homepage: 'https://coffeescript.org/',
    repository: 'https://github.com/jashkenas/coffeescript',
    icon: 'coffeescript.png',
    keywords: ['coffeescript'],
    name: 'CoffeeScript',
    darkInvert: true,
  },
  {
    homepage: 'https://typestrong.org/ts-node/',
    repository: 'https://github.com/TypeStrong/ts-node',
    icon: 'ts-node.png',
    keywords: ['ts-node'],
    name: 'TSNode',
    darkInvert: true,
  },
  {
    homepage: 'https://terser.org/',
    repository: 'https://github.com/terser/terser',
    icon: 'terser.png',
    keywords: ['terser'],
    name: 'Terser',
  },
  {
    homepage: 'https://gogocode.io/zh',
    repository: 'https://github.com/thx/gogocode',
    icon: 'gogocode.png',
    keywords: ['gogocode'],
    name: 'GoGoCode',
  },
  {
    homepage: 'https://rxjs.dev/',
    repository: 'https://github.com/ReactiveX/rxjs',
    icon: 'rxjs.png',
    keywords: ['rxjs'],
    name: 'RxJS',
  },
  {
    homepage: 'https://jestjs.io/',
    repository: 'https://github.com/facebook/jest',
    icon: 'jest.png',
    keywords: ['jest'],
    name: 'Jest',
  },
  {
    homepage: [
      {
        href: 'https://astexplorer.net/',
        title: '链接1',
      },
      {
        href: 'https://resources.jointjs.com/demos/rappid/apps/Ast/index.html',
        title: '链接2',
      },
    ],
    icon: 'https://astexplorer.net/favicon.png',
    keywords: ['ast'],
    name: 'ast',
  },
];
