const fs = require('fs')
const path = require('path')
const { execSync } = require('child_process')

const ICONS_DIR = path.resolve(__dirname, '../public/icons')
const SRC_DIR = path.resolve(__dirname, '../src')
const ICONS_TS_FILE = path.join(SRC_DIR, 'icons-map.ts')

function getBase64(filePath) {
  const data = fs.readFileSync(filePath)
  const ext = path.extname(filePath).slice(1).toLowerCase()
  const mimeType = ext === 'svg' ? 'image/svg+xml' : `image/${ext === 'jpg' ? 'jpeg' : ext}`
  return `data:${mimeType};base64,${data.toString('base64')}`
}

function generateIconsMap() {
  const files = fs.readdirSync(ICONS_DIR)
  const iconsMap = {}

  files.forEach(file => {
    if (file.match(/\.(png|jpg|jpeg|svg|gif|webp)$/i)) {
      const filePath = path.join(ICONS_DIR, file)
      iconsMap[file] = getBase64(filePath)
    }
  })

  const content = `// Auto-generated by scripts/build.js
// Do not edit manually

export const iconsMap = ${JSON.stringify(iconsMap, null, 2)}

export function getIconUrl(filename) {
  return iconsMap[filename] || ''
}
`

  fs.writeFileSync(ICONS_TS_FILE, content)
  console.log(`✓ Generated ${Object.keys(iconsMap).length} icons to src/icons-map.ts`)
}

function build() {
  console.log('Building lib...')
  generateIconsMap()
  execSync('npx vite build', {
    cwd: path.resolve(__dirname, '..'),
    stdio: 'inherit',
    env: { ...process.env, NODE_ENV: 'production' },
  })
}

// Watch mode
if (process.argv.includes('--watch')) {
  console.log('Starting watch mode...')

  // Initial build
  build()

  let isBuilding = false

  const debouncedBuild = () => {
    if (isBuilding) return
    isBuilding = true
    setTimeout(() => {
      try {
        build()
      } catch (e) {
        console.error('Build failed:', e.message)
      }
      isBuilding = false
    }, 100)
  }

  // Watch for icon changes
  fs.watch(ICONS_DIR, { recursive: true }, (eventType, filename) => {
    if (filename && filename.match(/\.(png|jpg|jpeg|svg|gif|webp)$/i)) {
      console.log(`\nIcon changed: ${filename}`)
      debouncedBuild()
    }
  })

  // Watch for source changes (excluding generated files)
  fs.watch(SRC_DIR, { recursive: true }, (eventType, filename) => {
    if (filename && filename.endsWith('.ts') && !filename.includes('icons-map')) {
      console.log(`\nSource changed: ${filename}`)
      debouncedBuild()
    }
  })

  console.log('Watching for changes...')
  console.log('Press Ctrl+C to stop')
} else {
  build()
}
