import fs from 'fs'
import path from 'path'

const ICONS_DIR = path.resolve(__dirname, '../public/icons')
const OUTPUT_FILE = path.resolve(__dirname, '../src/icons.ts')

function getBase64(filePath: string): string {
  const data = fs.readFileSync(filePath)
  const ext = path.extname(filePath).slice(1)
  const mimeType = ext === 'svg' ? 'image/svg+xml' : `image/${ext === 'jpg' ? 'jpeg' : ext}`
  return `data:${mimeType};base64,${data.toString('base64')}`
}

function generateIconsMap(): void {
  const files = fs.readdirSync(ICONS_DIR)
  const iconsMap: Record<string, string> = {}

  files.forEach(file => {
    if (file.match(/\.(png|jpg|jpeg|svg|gif|webp)$/i)) {
      const filePath = path.join(ICONS_DIR, file)
      iconsMap[file] = getBase64(filePath)
    }
  })

  const content = `// Auto-generated by scripts/generate-icons.ts
// Do not edit manually

export const iconsMap: Record<string, string> = ${JSON.stringify(iconsMap, null, 2)}

export function getIconUrl(filename: string): string {
  return iconsMap[filename] || ''
}
`

  fs.writeFileSync(OUTPUT_FILE, content)
  console.log(`Generated ${Object.keys(iconsMap).length} icons to src/icons.ts`)
}

generateIconsMap()
